### ISSUE TITLE
bower package name already taken

### ISSUE THREAD

**Issue by nharraud** [ljharb/qs#108]
Hi,

I have been trying to install this package using bower and just realised that the name "qs" is pointing to another repository:
http://bower.io/search/?q=qs
https://github.com/nire0510/qs

As this repository (hapijs/qs) contains a bower.json with "qs" as name, I supposed that it was published on bower.

**Comment by nharraud** [comment]
Also the version in the bower.json is 3.0 instead of 4.0

**Comment by nlf** [comment]
the version is synced, but you're right the name is already taken. at this point, frankly,  i'm torn between renaming it in bower and just dropping support for bower.

**Comment by nharraud** [comment]
It's quite frequent that packages have different names for github, bower and npm so renaming wouldn't be too bad. I often just read the github README to see how it is named, or follow the links when I find it on npm/bower.

**Comment by checat** [comment]
hapijs-qs is a good name

**Comment by viniciusgava** [comment]
Please, add in README.md the bower package.

**Comment by blowsie** [comment]
Is there a standalone single JS file that can be used instead of a bower package?

**Comment by arb** [comment]
I vote for dropping bower support, especially with a major release coming soon.

**Comment by AdriVanHoudt** [comment]
same, bower is DOA

**Comment by nlf** [comment]
i think that's exactly what's going to happen. qs@6.0.0 will remove support for everything but npm.

**Comment by ljharb** [comment]
Closing in favor of #129 which will remove bower support entirely.
