### ISSUE TITLE
Shouldn't `stringify` have an option for the `foo.bar.baz=x` format?

### ISSUE THREAD

**Issue by ikr** [ljharb/qs#119]
As `parse` has the `allowDots` option accepting that notation. Would you accept a pull request implementing that functionality?

**Comment by nlf** [comment]
I would accept a pull request to add dot formatting to stringify, sure.

**Comment by snow01** [comment]
Submitted PR -- https://github.com/ljharb/qs/pull/151

Please help pass it.

**Comment by ljharb** [comment]
Thanks!

**Comment by ljharb** [comment]
Closed by #151.
