### ISSUE TITLE
Different main in package.json and bower.json

### ISSUE THREAD

**Issue by AndrejGajdos** [ljharb/qs#128]
Hi, I use webpack and [history library](https://github.com/rackt/history) which has this project as a node module dependency. When I want to build the project I get error:

`Module not found: Error: Cannot resolve 'file' or 'directory' ./dist/qs.js in /Users/and/p/node_modules/history/node_modules/qs`

In package.json of this project is main file lib/index.js, but in bower.json dist/qs.js and when this project is downloaded as a node module dependency there is not dist folder. 

It only works when I change main of bower.json to lib/index.js.

**Comment by nlf** [comment]
yeah.. the whole bower/component support thing has been kind of a pain. i'm going to remove those configs entirely, as well as the dist directory.

**Comment by ljharb** [comment]
`dist` directory removed in ece065503ecc86e950d4a25e0e3f9c5d34c2ec72. v7.0.0 will remove bower/component support completely.

Closing this in favor of #129.
