### ISSUE TITLE
qs stringify with array of objects?

### ISSUE THREAD

**Issue by mmahalwy** [ljharb/qs#142]
```
{
      tickets: [
        {
          pricing_item_gid: activity.tickets[0].source_activity_refid,
          quantity: 1
        }
      ],
      start_date: this.state.selectedDate.format('YYYY-MM-DD'),
      end_date: this.state.selectedDate.clone().add(6, 'months').format('YYYY-MM-DD'),
      show_not_available_dates: true
    }
```
is stringed to be:
```
tickets%5B0%5D%5Bquantity%5D=1&start_date=2015-12-02&end_date=2016-06-02&show_not_available_dates=true
```

How come I get object object? 

Thanks!

**Comment by ljharb** [comment]
Can you provide a bit more information? Specifically, what is the value of `activity.tickets[0].source_activity_refid`? When I do `qs.parse('tickets%5B0%5D%5Bquantity%5D=1&start_date=2015-12-02&end_date=2016-06-02&show_not_available_dates=true')` I get:
```js
{
  tickets: [ { quantity: '1' } ],
  start_date: '2015-12-02',
  end_date: '2016-06-02',
  show_not_available_dates: 'true'
}
```

which seems correct except for the `pricing_item_gid` field - this implies that its value might be `undefined`?

**Comment by ljharb** [comment]
Happy to reopen, given more information.
