### ISSUE TITLE
maintain consistent version number in bower.json

### ISSUE THREAD

**Issue by shawnzhu** [ljharb/qs#147]
When installing qs via bower, I got this warning:

```
bower mismatch      Version declared in the json (5.2.0) is different than the resolved one (6.0.2)
```

Then I found the version in `bower.json` is still `5.0.2` but the release is `6.0.2`

**Comment by shawnzhu** [comment]
close since no bower fan here #129

**Comment by LukeSwart** [comment]
@shawnzhu Is this package still available on Bower? I tried `bower install qs --save`, but it downloaded the package from this repo: https://github.com/nire0510/qs

Is this package registered to another namespace on bower? Or is it no longer available?
