### ISSUE TITLE
/dist folder missing when using bower

### ISSUE THREAD

**Issue by sankethkatta** [ljharb/qs#148]
In `v6.0.0`, there was a `/dist` checked into the repository which worked for both bower and npm installs. 

However, now the `/dist` generation has been moved to `prepublish` in `package.json`, this only works for npm. Which breaks any workflows with bower that were depending on the built `qs.js` file being present.

One solution would be to generate `/dist` on one of the [bower hooks](http://bower.io/docs/config/#hooks).

**Comment by ljharb** [comment]
Per #129, this project will be removing bower support. v6.0 broke it anyways for non-ES6 browsers, and in 2016 it's long past time for folks to be using npm + browserify/webpack to consume JS assets.

I could certainly restore the `dist` directory briefly, prior to releasing v7.0 (no concrete date yet), but I'm not sure I see the benefit.

**Comment by sankethkatta** [comment]
Fully understand that bower support will be removed and there are much better ways of consuming JS assets. I created this issue up mainly because a minor version increase to `v6.0.2` broke our builds, `^` and the stricter `~` fetch the latest minor version, but thats more a semver / versioning issue.

Maybe just a notice on the README that bower support has been / will be dropped would be nice.

**Comment by ljharb** [comment]
That's a really fair point, *technically* removing `dist` is a breaking change in a non-major version bump.

I'll revert it for now, and wait to remove `dist` until v7.

**Comment by chrisknoll** [comment]
It seems this folder is gone again in 6.9.5 (I think it was there in 6.5.2).

**Comment by ljharb** [comment]
This was an unintentional regression in d4f6c32; i'll publish a v6.9.6 shortly that restores it.

While I'm committed to maintaining bower compatibility until v7, I would also strongly encourage you to migrate away from a 3-5 years deprecated curl wrapper.

**Comment by ljharb** [comment]
v6.9.6 is published, sorry for the inconvenience.

**Comment by chrisknoll** [comment]
Thank you so much @ljharb.
