### ISSUE TITLE
'skipNulls' option of 'stringify()' method doesn't work

### ISSUE THREAD

**Issue by Janekk** [ljharb/qs#155]

**Comment by ljharb** [comment]
@Janekk can you be more specific? Do you have sample input, expected output, and actual output? Which version of `qs` are you using?

**Comment by Janekk** [comment]
@ljharb version that I use is `6.1.0`

for object like:

```
var query = {attr1: 'abc', page: null};

var stringified = qs.stringify(query, {skipNulls: true});
```

`stringified` will return `attr1=abc&page=`

**Comment by ljharb** [comment]
@Janekk for me, I get `qs.stringify({attr1: 'abc', page: null}, { skipNulls: true }) === 'attr1=abc'`. Are you sure there's no typo in the option, or the query, or that you in fact are using the latest version of qs?

**Comment by Janekk** [comment]
@ljharb yeap, you're right. I must have mistyped something.. It works as expected. We can close this issue :)
