### ISSUE TITLE
insonsistent behaviour when parsing nested queries

### ISSUE THREAD

**Issue by seriousManual** [ljharb/qs#157]
when nested parameters are specified in an URL (like `foo[bar]=bax`) the querystring module does not consistently parse these nested elements:

````
[mer@vm024 express]$ node
> var qs = require('qs')
undefined

> qs.parse('c[123]=1')
{ c: { '123': '1' } }

> qs.parse('c[12]=1')
{ c: [ '1' ] }

````

the expected result in the second example would be `{c: {'12': '1'}}`

**Comment by seriousManual** [comment]
just found a test case that adresses this specific behaviour which shows that is intended behaviour:

````
st.deepEqual(qs.parse('a[20]=a'), { a: ['a'] });
st.deepEqual(qs.parse('a[21]=a'), { a: { '21': 'a' } });
````

i dont understand the reasoning behind this behaviour.

**Comment by ljharb** [comment]
See under https://github.com/ljharb/qs#parsing-arrays - "qs will also limit specifying indices in an array to a maximum index of 20", and "This limit can be overridden by passing an arrayLimit option".

**Comment by seriousManual** [comment]
hi,
thank you for your answer!

i found that paragraph shortly after posting this issue, unfortunately the arrayLimit option does not really help as I'm using 'qs' indirectly via express which does not give me the oportunity to specify the query parsing behaviour.

**Comment by ljharb** [comment]
In that case I'd recommend filing an issue on `express` to allow that parsing option to be passed through - there's nothing `qs` can do about how `express` chooses to call it :-/

**Comment by seriousManual** [comment]
is there a reason that actually the index of 20 is the limit for the change in parsing arrays/objects?

**Comment by ljharb** [comment]
I'm not sure - it was defined before I took over the project. I'm assuming it was arbitrary.

**Comment by seriousManual** [comment]
all right, thank you!
