### ISSUE TITLE
Parsing deeply nested arrays parses into object

### ISSUE THREAD

**Issue by aroc** [ljharb/qs#158]
When parsing a deeply nested array, the array gets parsed into an object.

Parsing: `qs.parse("[filters][0][property_value][0]=testing"))`
Returns: `filters: { property_value: ['testing'] }`

But, parsing: `qs.parse("[steps][0][filters][0][property_value][0]=testing"))`
Returns: `steps: [{ filters: [{ property_value: { '0': 'testing' } }] }]`

Is this expected? Is there a way I can get the second example to return the `property_value` as an array, like so: `property_value: ['testing']` ?

Live example on tonic:
https://tonicdev.com/aroc/571ec5fc40717c110098df09

Thanks so much!!

**Comment by aroc** [comment]
Here's another example stringifying with `qs` then immediately parsing, but parsed version produces an object rather than an array:
https://tonicdev.com/aroc/qs-stringify-then-parse-bug

**Comment by ljharb** [comment]
Without the indexes (which generally i wouldn't expect in an array) I get:
```js
qs.parse('[property_value][]=testing');
  // => { property_value: [ 'testing' ] }
qs.parse('[filters][][property_value][]=testing');
  // => { filters: [ { property_value: [ 'testing' ] } ] }
qs.parse('[steps][][filters][][property_value][]=testing');
  // => { steps: [ { filters: { property_value: [ 'testing' ] } } ] }
```

Where do the zeroes come from?

**Comment by aroc** [comment]
The zeros come from calling `qs.stringify`. Check out my example code here: https://tonicdev.com/aroc/qs-stringify-then-parse-bug

**Comment by ljharb** [comment]
Ah, gotcha. Thanks, I'll look into this - I'm not sure whether this is a bug or not, but it's definitely strange.

**Comment by aroc** [comment]
Cool, thanks! I'll try and dig around the source as well and see if I can identify a potential bug. (Great lib btw, I've used it in several large scale production projects now.)

**Comment by aroc** [comment]
Ah, figured it out as I tried to debug the issue. Turns out, I just need to bump the `depth` option to `6` from the default of `5`. Argggg. Sorry about this! Closing this issue.

**Comment by ljharb** [comment]
aha, thanks for clarifying :-) i'm still new to maintaining this project so i need to learn the ins and outs of it better
