### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by williamoliveira** [ljharb/qs#159]
Would it be possible to make Date stringfy format configurable? maybe receiving a callback in the options so one could use momentjs to format it as he wants

**Comment by ljharb** [comment]
What's the use case for sending a Date as anything other than an ISO string?

**Comment by williamoliveira** [comment]
To match the format being used in the other side of the API or App, maybe its Unix timestamp or a custom format

**Comment by ljharb** [comment]
If someone wants to submit a PR, it'd be worth looking at how it impacts the API to support that.
