### ISSUE TITLE
Deeply nested elements will mess up keys.

### ISSUE THREAD

**Issue by jaxoncreed** [ljharb/qs#170]
When dealing with deeply nested elements the keys will begin to be added to a string rather than continue nesting:

Example:
`?shweep[weep][beep][meep][leep][teep][moop][goop]=10`

Will yield:

```
{  
   "shweep":{  
      "weep":{  
         "beep":{  
            "meep":{  
               "leep":{  
                  "teep":{  
                     "[moop][goop]":"10"
                  }
               }
            }
         }
      }
   }
}
```

But should yield:

```
{  
   "shweep":{  
      "weep":{  
         "beep":{  
            "meep":{  
               "leep":{  
                  "teep":{  
                    "moop": {
                      "goop": "10"
                    }
                  }
               }
            }
         }
      }
   }
}
```

**Comment by ljharb** [comment]
This is documented in the [readme](https://github.com/ljharb/qs#parsing-objects) and is covered by the "depth" option, which defaults to `5` (weep + beep + meep + leep + teep). Pass `{ depth: 10 }` and you'll get what you expect.
