### ISSUE TITLE
Filter function for parsing, or some way to turn values into arrays. 

### ISSUE THREAD

**Issue by spoeken** [ljharb/qs#172]
I would like some way to turn this:
`fruits=apple,banana,mango&drinks=gt,cuba-libre,beer`
into this:
`{fruits:['apple','banana','mango'],drinks:['gt','cuba-libre','beer']`

I've tried to use the filter function, but realized it doesn't work for parsing. But this makes sense to me:

	function filterFunc(prefix, value) {
		console.log('Filtering');
	  if (value.indexOf(',')) {
	    return value.split(',');
	  } else {
	  	console.log('No match');
	  }
	  return value;
	}

	const search = window.location.search.slice(1);
	const filterArray = qs.parse(search, { filter: filterFunc });
	console.log(filterArray);

**Comment by ljharb** [comment]
The proper way is to use array syntax in your query string: `fruits[]=apple&fruits[]=banana&fruits[]=mango` etc

**Comment by spoeken** [comment]
Thanks @ljharb
thats pretty clear in the docs as well.
I was hoping there was a way to tweak this to my liking, with qs.
Not a big deal tho, made a separate function for it.

**Comment by ljharb** [comment]
I think that could be added to `qs` given a use case, but supporting nonstandard querystrings isn't a great one :-/

**Comment by JasonCust** [comment]
@ljharb I just ran into use case for supporting this. From the JSON API specification for [sparse field sets](http://jsonapi.org/format/#fetching-sparse-fieldsets):

> The value of the fields parameter MUST be a comma-separated (U+002C COMMA, “,”) list that refers to the name(s) of the fields to be returned.

The example query string provided is: `/articles?include=author&fields[articles]=title,body&fields[people]=name`

This format is also used by other parameters such as `include` and `sort`.
