### ISSUE TITLE
Add support for RFC 1738

### ISSUE THREAD

**Issue by slavafomin** [ljharb/qs#173]
Hello!

Thank you for this great module!

I'm using it to stringify API request query parameters and then generate MD5 hash of the resulted string. However, the server is expecting this string to be in RFC 1738 format, not in RFC 3986. This leads to incorrect hash, because spaces should be represented as `+`, not as `%20`.

It looks like server uses PHP's [http_build_query](http://php.net/manual/en/function.http-build-query.php) function to generate the query string and it uses RFC 1738 by default.

Could you please implement support for both RFC 1738 and RFC 3986 formats? It will make this library more compatible with different technologies.

Right now I have to use this workaround:

```js
let queryAsString = queryString
  .stringify(data)
  .replace(/%20/g, '+')
;
```

Thank you!

**Comment by ljharb** [comment]
https://github.com/ljharb/qs/issues/152#issuecomment-211534354 seems relevant.

Note that you can already pass a custom `encoder` function to `stringify`, that will let you do the replacement there, and a custom "decoder" function to "parse".

**Comment by slavafomin** [comment]
I would suggest this API:

```js
const qs = require('qs');

let result = qs.stringify(data, {
    format: qs.RFC1738,
//  format: qs.RFC3986
});
```

**Comment by ljharb** [comment]
That's really not a bad idea at all.

Are there other RFCs that we'd want to support?

@slavafomin would you be willing to make a PR that adds these formats to both `parse` and `stringify`?

**Comment by slavafomin** [comment]
@ljharb I would love to do so, but my time is extremely limited these days. I'm having a hard time supporting my own libraries right now. Sorry, I hope someone will have the time to implement this, because it looks like a good idea.

**Comment by Max-Kolodezniy** [comment]
Done here. API interface is exactly the same as described above
https://github.com/ljharb/qs/pull/174

**Comment by ljharb** [comment]
Done in #174.

**Comment by slavafomin** [comment]
Great job!
