### ISSUE TITLE
filter using a function doesn't work.

### ISSUE THREAD

**Issue by jpettitt** [ljharb/qs#176]
[![view on requirebin](http://requirebin.com/badge.png)](http://requirebin.com/?gist=8edddc53bea09b73ef9f74ead4056561)

Basically if you tell it to stringify `{ x: 1 }` with a filter function the function is called with `prefix` set to an empty string and `value` set to  `{ x: 1}`  (expecting `prefix === 'x'` and `value === 1`)

**Comment by ljharb** [comment]
If you look at the [test](https://github.com/ljharb/qs/blob/master/test/stringify.js#L385), the filter function is designed to call the first time with an empty prefix, and the entire object.

In other words, the *second* call should get `'x', 1` as arguments: http://requirebin.com/?gist=5b75dbff59cc5b97ad231fcc9f575b56
