### ISSUE TITLE
Decoding and parsing misbehaving

### ISSUE THREAD

**Issue by razorcd** [ljharb/qs#179]
Parsing URL encoded params is not returning the correct result in one pass. (I am using TypeScript)

```
qs.parse('mm%3D100000001%26counter%3D2')
-> {mm=100000001&counter=2: ""}
```

```
qs.parse('mm=100000001&counter=2')
-> {mm: "100000001", counter: "2"}
```

Is this a bug or is there another way to handle this using `qs`.

**Comment by ljharb** [comment]
Yes - your initial example is double-encoded - ie, it is not a valid query string.

It's more luck that `qs.parse` decodes it for you - but it should be decoded by your webserver (or `window.location.search` before being passed to `qs.parse`.

**Comment by razorcd** [comment]
thanks for your help.
This did the trick:  
```
qs.parse(decodeURIComponent('mm%3D100000001%26counter%3D2'))
-> {mm: "100000001", counter: "2"}
```
