### ISSUE TITLE
Option to not collapse arrays with missing indices.

### ISSUE THREAD

**Issue by JC3** [ljharb/qs#181]
The following test:

    $ node -pe 'require("qs").parse("option[1]=1&text[0]=&text[1]=&text[2]=")'

Produces:

    { option: [ '1' ], text: [ '', '', '' ] }

The `option` array is collapsed and the missing index 0 is removed. According to the qs documentation, this behavior is intentional. However, it causes problems when handling arrays of checkboxes on a form with e.g. body-parser.

Consider:

index.js:

    var express = require("express");
    var site = express();
    
    site.use(require("body-parser").urlencoded({extended:true}));
    
    site.get("/", function (req, res) {
    	res.sendFile(__dirname + "/test.html");
    });
    
    site.post("/form", function (req, res) {
    	res.json(req.body);
    });
    
    site.listen(8081);

test.html:

    <html>
    	<body>
    		<form method="post" action="/form">
    			<input type="checkbox" name="option[0]" value="1">
    			<input type="checkbox" name="option[1]" value="1">
    			<input type="checkbox" name="option[2]" value="1"><br>
    			<input type="text" name="text[0]"><br>
    			<input type="text" name="text[1]"><br>
    			<input type="text" name="text[2]"><br>
    			<button type="submit">Submit</button>
    		</form>
    	</body>
    </html>

In that example, if I were to check only `option[1]`, I verify that the index is set correctly by inspecting the request in Chrome, body contents are:

    option[1]:1
    text[0]:
    text[1]:
    text[2]:

Yet qs collapses the `option` array and body-parser ultimately produces the following in `req.body`:

    {"option":["1"],"text":["","",""]}

Similarly, if I were to check `option[0]` and `option[2]`, the request body would have:

    option[0]:1
    option[2]:1
    text[0]:
    text[1]:
    text[2]:

But it would be parsed to:

    {"option":["1","1"],"text":["","",""]}

All information about which checkbox was checked is lost.

The only way, then, to parse checkbox arrays on forms is workarounds like the clever but hacky one at http://stackoverflow.com/a/41093135, which basically involves hidden inputs with the same name as the checkboxes, then using `Array.isArray()` to determine if a result is true or false.

I had originally opened this issue at https://github.com/expressjs/body-parser/issues/211 before I knew it was qs.

To that end, I'd like an option to *not* collapse arrays, such that the previous examples yield things like:

    {"option":[null,"1"]}

Or:

    {"option":["1",null,"1"]}

This would make parsing arrays of checkboxes on forms possible, which it currently is not without trickery.

**Comment by ljharb** [comment]
The typical way this is solved, across all server frameworks, is for each checkbox, prepending a hidden input with the same name and an explicit value.

In other words:
```html
<html>
	<body>
		<form method="post" action="/form">
			<input type="hidden" name="option[0]" value="0">
			<input type="checkbox" name="option[0]" value="1">
			<input type="hidden" name="option[1]" value="0">
			<input type="checkbox" name="option[1]" value="1">
			<input type="hidden" name="option[2]" value="0">
			<input type="checkbox" name="option[2]" value="1"><br>
			<input type="text" name="text[0]"><br>
			<input type="text" name="text[1]"><br>
			<input type="text" name="text[2]"><br>
			<button type="submit">Submit</button>
		</form>
	</body>
</html>
```

That way, an unchecked checkbox still gets submitted as a falsy value, and you don't have to infer anything.

The other alternative is to use an alphanumeric object key as the part inside the brackets - `0`, `1`, etc are for array indices, and usually that means you want a list.

**Comment by JC3** [comment]
@ljharb That's almost the workaround, but an unchecked checkbox doesn't get a falsey value in that case.

In your HTML snippet, an unchecked box gets the scalar value `"0"`. A checked box gets the array value `["0","1"]` (qs packs same-named values into an array). Both of these are truthy (the string "0" is truthy). So if I were to check `option[1]` in that snippet then post, it would be parsed as:

    {"option":["0",["0","1"],"0"],"text":["","",""]}

And if you were to do something like:

    option.map(item => (item ? true : false))

You'd always end up with trues:

    [true, true, true]

So what you'd *actually* have to do in that case is something weird like:

    option.map(item => Array.isArray(item))

To produce the correct value array:

    [false,true,false]

And actually this is precisely the workaround given in that linked SO post. It's a weird thing to have to do.

**Comment by ljharb** [comment]
That's true. Have you considered naming your fields as `option[]` instead, and using the values (instead of array positions) to indicate which box was checked?

**Comment by JC3** [comment]
@ljharb I have, that's another viable option. So is client-side JavaScript to build and submit a full array. Basically it all boils down to extra-processing-required with many ways to skin that cat. But if I could choose to not collapse arrays, the results could be used directly.

**Comment by ljharb** [comment]
I think that semantically, the best bet is `option[]` - I don't understand why you'd want to provide explicit indexes on what is semantically a list.

Effectively, the option you're requesting would be one that either created sparse arrays, or filled in the empty values with an explicit `null` or `undefined` - sparse arrays are a horrifically bad practice, very slow, and should never be used; and the latter could cause a memory issue where someone POSTs to your server with `foo[9999999]`.

If you prefer not to name your field as if it's a list, you may want to use the `parseArrays` option, which will avoid ever creating an array and instead create an object with numeric keys.

**Comment by JC3** [comment]
In my specific case the forms are generated dynamically. Numeric indexed arrays are the only straightforward option. There is no good way around it.

The issue with `foo[9999999]` is solvable by allowing a user-specified array size limit alongside the option to not collapse arrays. I already see an `arrayLimit` option in the documentation.

I have not played with `parseArrays`, I am not entirely sure how to twiddle those options through *body-parser* but I'll see what else I can come up with.

**Comment by ljharb** [comment]
`qs` doesn't do that, browsers do. Unchecked checkboxes aren't submitted by browsers.

**Comment by ljharb** [comment]
true, `arrayLimit` would also apply here.

I guess I'm just not understanding why it's not an option to omit numbered indexes in checkbox names - there's not really a reason *to* ever include numeric indexes inside the brackets on any form element. That's usually used for namespacing - ie, some alphanumeric identifier.

**Comment by JC3** [comment]
I meant that `qs` removes the gaps in the array; the only remnants of unchecked checkboxes the browsers give us.

Anyways, one simple use case for indexed items is when you are dynamically adding sets of inputs to a page. Numeric indices are your only straightforward choice for this.

For a working case see, for example, phpMyAdmin. In the "new columns" page, for example, you can choose to add an arbitrary number of new database columns. The form inputs for each of the column properties are given numeric indices. There's no other good way to do it.

Or, consider for example the following Jade/Pug template:

    - for (var n = 0; n < someExternalParameter; ++ n) {
        input(type="text", name="description["+n+"]")
        input(type="checkbox", name="option["+n+"]")
    - }

Things like this are really not unusual. And there are certainly workarounds, e.g. not using `[]` and instead encoding indices into names and parsing them back out afterwards, but it doesn't need to be that way, and *isn't* that way when dealing with server-side systems that don't collapse array parameters.

**Comment by ljharb** [comment]
You can dynamically add `option[]` with no numerical indices - there's zero reason you need them for single options - if you have multiple options, the better choice would be to pick a unique alphanumeric name - for example, `description["item_" + n]` is a very straightforward choice, is trivial to iterate on the other side.

I'll think more about this option - creating sparse arrays is just not a good idea, so it'd need to respect `arrayLimit` and also pick `null` or `undefined` to fill out the empty items.

**Comment by denizdogan** [comment]
I'm running into this limitation as well. My situation looks like this, with radio buttons:

    Title       1     2     3  
    --------------------------
    Foo        ( )   ( )   ( )
    Bar        (*)   ( )   ( )
    Baz        ( )   (*)   ( )
    Qux        ( )   ( )   (*)

So the user chooses a value between 1-3, or nothing at all, for each title. The titles are dynamically generated. In this case, you need the "indexed field names", like title[0], title[1], etc. to determine which title each value applies to. I can work around this using the trick with hidden fields, but it would be nice if this was supported out of the box!

**Comment by ljharb** [comment]
Why are the titles indexed instead of ordered by name?

**Comment by denizdogan** [comment]
@ljharb I'm not sure what you mean... The titles are represented as strings in an array field in a MongoDB document.

**Comment by ljharb** [comment]
What happens if a user chooses the second title, and before they submit it, the list of titles is updated on the server?

(In other words, I'm suggesting not coupling "the order in mongo" to "your browser/server protocol")

**Comment by denizdogan** [comment]
@ljharb There's a number of ways I work around the limitation, I'm using the hidden fields trick today with some processing of the submitted data in the backend code. The example I posted is from a real-world application and mostly a response to your previous comment:

>I don't understand why you'd want to provide explicit indexes on what is semantically a list

**Comment by ljharb** [comment]
Thank you for the example! I guess I'm just suggesting that the browser and server not communicate any information via ordering, but via more explicit methods - no matter how it's stored in a database.
