### ISSUE TITLE
stringify doesn't encode empty arrays

### ISSUE THREAD

**Issue by christensson** [ljharb/qs#186]
`qs.stringify({ a: [] })` results in an empty string `""`. And thus `qs.parse( qs.stringify({ a: [] }) )` results in `{}`.

What I would want is that `qs.parse( qs.stringify({ a: [] }) )` results in `{ a: [] }`. Any ideas?

**Comment by ljharb** [comment]
Why? Query strings typically only have contents when there's stuff there - ie, an empty array *is* nothing.

**Comment by christensson** [comment]
Yes, I can agree to that, but consider the following example `qs.stringify({ a: { b: [] } })`. What is transfered is the "knowledge" that a contains b and that it is b that is an empty list.

To give a bit of background, what I'm actually trying to encode to a query-string is a mongodb query looking like this: `{ _id: { $in: idArray } }` where idArray is an array which might be empty. This interpretation of the query is match all mongodb documents that have an _id field that is equal to one of the elements in idArray. With qs.stringify and idArray being empty it is encoded to `{}` which if used as a mongdb query matches everything where instead `{ _id: { $in: [] } }` would match nothing...

**Comment by ljharb** [comment]
That sounds like a mongo-specific issue that would be better solved by falling back to `{ _id: { $in: [] } }` when the object is empty - or, by JSON-encoding the query parameters as a single field. In other words, I don't think HTTP query params are the proper vehicle to convey all this information.

**Comment by christensson** [comment]
OK, I understand what you are saying. I will keep my current solution where I encode the information.
