### ISSUE TITLE
Parse ignoring empty array brackets

### ISSUE THREAD

**Issue by Boazc** [ljharb/qs#190]
I am using the parse option, trying to parse a query string with empty array brackets and nested elements:

queryString = by_value_range[fields][][name]=sku_count&by_value_range[fields][][min]=20&by_value_range[fields][][max]=50&by_value_range[fields][][name]=marketplace&by_value_range[fields][][min]=20&by_value_range[fields][][max]=122

parse(query)
returns

A "fields" array with only one element instead of two, it just ignores the empty brackets.
Is there any parameter that I need to pass that I have missed here?

**Comment by ljharb** [comment]
```js
qs.parse('by_value_range[fields][][name]=sku_count&by_value_range[fields][][min]=20&by_value_range[fields][][max]=50&by_value_range[fields][][name]=marketplace&by_value_range[fields][][min]=20&by_value_range[fields][][max]=122').by_value_range.fields
```
gives me
```js
[ { name: [ 'sku_count', 'marketplace' ],
    min: [ '20', '20' ],
    max: [ '50', '122' ] } ]
```

Are you saying you'd expect it to give you
```js
[ { name: [ 'sku_count' },
  { min: 20 },
  { max: 50 },
  { name: 'marketplace' },
  { min: 20 },
  { max: 122 } ]
```
?

(Either a nested `[]` is treated as the same array item, or it'd need to be treated as a new array item on every appearance)

**Comment by Boazc** [comment]
I solved it with the indices, which does the job well.
When you use the brackets format it doesn't recognize it as an array if there is no implicit key: value inside the array.

**Comment by ljharb** [comment]
Right, there'd be no way for it to link together the first `[][name]` and `[][min]` without also linking the second `[][name]` and `[][min]`.
