### ISSUE TITLE
qs.stringify() doesn't work on an object (code provided)

### ISSUE THREAD

**Issue by jakey-wan-kenobi** [ljharb/qs#194]
When I run this in a Node 7.2 environment: 

```
const attach = qs.stringify({
    'attachments': [{
      'text': 'Choose a game to play',
      'fallback': 'You are unable to choose a game',
      'callback_id': 'wopr_game',
      'color': '#3AA3E3',
      'attachment_type': 'default',
      'actions': [
        {
          'name': 'chess',
          'text': 'Chess',
          'type': 'button',
          'value': 'chess'
        },
        {
          'name': 'maze',
          'text': "Falken's Maze",
          'type': 'button',
          'value': 'maze'
        },
        {
          'name': 'war',
          'text': 'Thermonuclear War',
          'style': 'danger',
          'type': 'button',
          'value': 'war',
          'confirm': {
            'title': 'Are you sure?',
            'text': 'Wouldn\'t you prefer a good game of chess?',
            'ok_text': 'Yes',
            'dismiss_text': 'No'
          }
        }
      ]
    }]
  }

console.log(attach)

```

I get this: 
```
attachments=
```

Any idea why I can't stringify this object?

**Comment by ljharb** [comment]
When I use your example - but add the missing `);` at the end - I get: `'attachments%5B0%5D%5Btext%5D=Choose%20a%20game%20to%20play&attachments%5B0%5D%5Bfallback%5D=You%20are%20unable%20to%20choose%20a%20game&attachments%5B0%5D%5Bcallback_id%5D=wopr_game&attachments%5B0%5D%5Bcolor%5D=%233AA3E3&attachments%5B0%5D%5Battachment_type%5D=default&attachments%5B0%5D%5Bactions%5D%5B0%5D%5Bname%5D=chess&attachments%5B0%5D%5Bactions%5D%5B0%5D%5Btext%5D=Chess&attachments%5B0%5D%5Bactions%5D%5B0%5D%5Btype%5D=button&attachments%5B0%5D%5Bactions%5D%5B0%5D%5Bvalue%5D=chess&attachments%5B0%5D%5Bactions%5D%5B1%5D%5Bname%5D=maze&attachments%5B0%5D%5Bactions%5D%5B1%5D%5Btext%5D=Falken%27s%20Maze&attachments%5B0%5D%5Bactions%5D%5B1%5D%5Btype%5D=button&attachments%5B0%5D%5Bactions%5D%5B1%5D%5Bvalue%5D=maze&attachments%5B0%5D%5Bactions%5D%5B2%5D%5Bname%5D=war&attachments%5B0%5D%5Bactions%5D%5B2%5D%5Btext%5D=Thermonuclear%20War&attachments%5B0%5D%5Bactions%5D%5B2%5D%5Bstyle%5D=danger&attachments%5B0%5D%5Bactions%5D%5B2%5D%5Btype%5D=button&attachments%5B0%5D%5Bactions%5D%5B2%5D%5Bvalue%5D=war&attachments%5B0%5D%5Bactions%5D%5B2%5D%5Bconfirm%5D%5Btitle%5D=Are%20you%20sure%3F&attachments%5B0%5D%5Bactions%5D%5B2%5D%5Bconfirm%5D%5Btext%5D=Wouldn%27t%20you%20prefer%20a%20good%20game%20of%20chess%3F&attachments%5B0%5D%5Bactions%5D%5B2%5D%5Bconfirm%5D%5Bok_text%5D=Yes&attachments%5B0%5D%5Bactions%5D%5B2%5D%5Bconfirm%5D%5Bdismiss_text%5D=No'`

That's in node v7.4 - in v7.2, I get the same.

**Comment by ljharb** [comment]
@jakey-wan-kenobi Is this still an issue? I'm happy to reopen it if so.
