### ISSUE TITLE
weird results with file paths in url

### ISSUE THREAD

**Issue by xblox** [ljharb/qs#196]
Hi,
I am not sure this is intended:

```js
console.log(qs.parse('http://127.0.0.1:5555/xideve/preview/workspace_user/AM2.html?userDirectory=C%3A%5CUsers%5Cmc007%5CDocuments%5CControl-Freak'));

//prints:

{ 'http://127.0.0.1:5555/xideve/preview/workspace_user/AM2.html?userDirectory': 'C:\\Users\\mc007\\Documents\\Control-Freak' }

```

Of course I'd have expected an object: 

{
  'userDirectory': 'C:\Users\mc007\Documents\Control-Freak'
}

I am aware that absolute file paths, encoded with encodeURIComponent could confuse the parser. 

Any idea ? 
thanks a lot for your library!

**Comment by xblox** [comment]
there are even different results when running qs.parse on windows and linux for that url.

**Comment by ljharb** [comment]
`qs.parse` expects a query string - it's not valid to provide it a full URL.

Try `qs.parse('?userDirectory=C%3A%5CUsers%5Cmc007%5CDocuments%5CControl-Freak')`

**Comment by xblox** [comment]
too funny, thanks a lot

**Comment by xblox** [comment]
@ljharb so I tested `'?userDirectory=C%3A%5CUsers%5Cmc007%5CDocuments%5CControl-Freak'`
but this gives me: 

`{ '?userDirectory': 'C:\\Users\\mc007\\Documents\\Control-Freak' }`

doesn't really look right to me.
