### ISSUE TITLE
No compatible version found: qs@6.4.0

### ISSUE THREAD

**Issue by lz000** [ljharb/qs#203]
Just this morning (3/6/2017), when I tried installing qs@6.4.0 with command "npm install qs@6.4.0", I got error "No compatible version found: qs@6.4.0", I checked the npm registry https://www.npmjs.com/package/qs but I do see 6.4.0 is available. Anyone know what's going on?

below is the full error:
npm ERR! notarget No compatible version found: qs@6.4.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 6.3.1, 6.3.0, 6.2.2, 6.2.1, 6.2.0, 6.1.1, 6.1.0, 6.0.3, 6.0.2,
 6.0.1, 6.0.0, 5.2.1, 5.2.0, 5.1.0, 5.0.0, 4.0.0, 3.1.0, 3.0.0, 2.4.2, 2.4.1, 2.
4.0, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.0
, 2.0.0, 1.2.2, 1.2.1, 1.2.0, 1.1.0, 1.0.2, 1.0.1, 1.0.0, 0.6.6, 0.6.5, 0.6.4, 0
.6.3, 0.6.2, 0.6.1, 0.6.0, 0.5.6, 0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.
2, 0.4.1, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.0, 0.0.7, 0.0.6, 0.0.5, 0.0.4,
0.0.3, 0.0.2, 0.0.1

**Comment by ljharb** [comment]
When I run `npm show qs` i see the latest as 6.4.0 - any chance you're using a nonpublic registry? What's `npm config get registry` say?

**Comment by lz000** [comment]
Thanks, I tried again and it worked. Mast be a temporary issue
