### ISSUE TITLE
Option to ignore leading '?' in a search string

### ISSUE THREAD

**Issue by jinalskothari** [ljharb/qs#209]
I use react-router. It exposes a `location.search` string property. It includes the '?' character in the search string. I could write some code to remove it before I give to qs to parse; however it would be nice if qs could do that.

The api could look like this 
```javascript
var parsedObj = qs.parse('?itemType=theBest&itemCost=1gazillion', {ignoreLeadingQuestion:true})
assert.notEqual(parsedObj, {'?itemType':'theBest', itemCost:'1gazillion'})
```

**Comment by ljharb** [comment]
Duplicate of #177.
