### ISSUE TITLE
not expected

### ISSUE THREAD

**Issue by Jiiun** [ljharb/qs#210]
pic_text: qs.stringify([Array(0), ""]) -> 
![image](https://cloud.githubusercontent.com/assets/13991287/26274032/3f59dda6-3d71-11e7-8881-d24db0a813b0.png)

**Comment by ljharb** [comment]
Why is that not expected?

An empty array has no representation that can be sent to the server - so `[[], '']` is the same as `[, '']` - which is why you just get a `[1]`.

**Comment by Jiiun** [comment]
there's no pic_text[0], it is strange

**Comment by ljharb** [comment]
Right - because it's an empty array, so there's nothing to go there.

**Comment by Jiiun** [comment]
![image](https://cloud.githubusercontent.com/assets/13991287/26274128/b949167e-3d74-11e7-9caa-bd68035a8102.png)
I used reqwest to submit the same data, it is empty too!  But more reasonable. I should try another way to communicate with the server. Thank you~
by the way~ your avatar is really cool^_^
