### ISSUE TITLE
Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by dynnamitt** [ljharb/qs#211]
Getting this error in an app that is using a limited amount of mem and lots of requests
see  https://github.com/auth0/passport-auth0/issues/45

**Comment by ljharb** [comment]
This looks like a malformed request, and an absence of a "limit" - can you provide the JS code that's invoking `qs.parse`?

**Comment by dynnamitt** [comment]
I'm working on a long running test now to see if latest request+qs have the same issue. 
I think the trigger is a passport.deserialze() call 3 layers above this lib.

**Comment by ljharb** [comment]
I'm going to close this, but will be happy to reopen if it turns out to be a qs issue.
