### ISSUE TITLE
boolean value is stringified as string 

### ISSUE THREAD

**Issue by sht5** [ljharb/qs#214]
if you stringify an object with a boolean key\value and then parse it the boolean is parsed as  a string 

`const qs = require('qs');
const x = {a:2,b:false};
const str = qs.stringify(x);
const xAfter = qs.parse(str);
console.log(JSON.stringify(xAfter));
//{a:2,b:"false"}`

**Comment by ljharb** [comment]
Everything that goes over the wire is a string; I'm not sure what else it would be?

**Comment by sht5** [comment]
I was under the impression that when parsing back i would get the same
object i stringified. I see now this is not supported

**Comment by ljharb** [comment]
Unfortunately, that's absolutely not a valid expectation when dealing with query strings - it's not even a valid expectation when dealing with JSON.

**Comment by jackypan1989** [comment]
To extend query parser to handle 'true' / 'false' / 'null' in qs
https://github.com/jackypan1989/express-query-parser

**Comment by carpben** [comment]
The default should be to return true as a string. But it would be nice if you can opt in to parse a true/false strings as booleans.

**Comment by ljharb** [comment]
@carpben you should be able to do that by providing a custom encoder function.

**Comment by carpben** [comment]
Done. Thanks!

**Comment by carpben** [comment]
I tried this:  
```
qs.parse(history.location.search, { 
   ignoreQueryPrefix: true ,
   decoder: str => (str==="false")? false : (str==="true")? true : str
 })
```
But this led to a bug, changing the keys for the returned object. For example, when logging the parsed object: 
`{activities%5B0%5D: "16"}`

**Comment by ljharb** [comment]
You do actually have to still decode things. The decoder gets additional arguments that may help.
