### ISSUE TITLE
Please expose toRFC3986 and toRFC1738

### ISSUE THREAD

**Issue by Noitidart** [ljharb/qs#216]
I need to use toRFC3986 sometimes. Like when generating Twitter oauth token signature.

Currently I do this:

```js
import { encode as qsEncode  } from 'qs/lib/utils'
import { formatters as qs_formatters  } from 'qs/lib/formats'

export function toRFC3986(str) {
	return qs_formatters['RFC3986'](qsEncode(str));
}

export function toRFC1738(str) {
	return qs_formatters['RFC1738'](qsEncode(str));
}
```

Would it make sense to expose this from qs?

**Comment by ljharb** [comment]
It's already exposed, under that deep path :-)

The API of a package includes everything that's reachable; it's not just what's on the main export.

**Comment by Noitidart** [comment]
Thanks very much @ljharb for the fast reply. I tried to understand that but I can't seem to access it, may you please share some code.

**Comment by ljharb** [comment]
It's exposed in the way you're importing it in your original post - `require('qs/lib/formats').formatters. RFC3986` and `require('qs/lib/formats').formatters. RFC1738`.

**Comment by Noitidart** [comment]
Ooo, but don't i have to run encode on it first?

**Comment by ljharb** [comment]
For the value, yes - not for the key or prefix though: https://github.com/ljharb/qs/blob/master/lib/stringify.js#L62-L64

**Comment by Noitidart** [comment]
Ah thanks my need was actually for outside of query string. Like I was using this on a url and other parameters. It's what some APIs ask for, Twitter API is the one I was working on today. So the only way is to actually wrap `encode` as I did in OP huh?

I'll close this out thanks so much for leaving it open for me to close.

**Comment by ljharb** [comment]
Yes, I think that's probably best :-)

**Comment by Noitidart** [comment]
Thanks so much brother for your support! I really appreciate it, all within a few hours too! :)
