### ISSUE TITLE
Option ignoreQueryPrefix fails in node environment

### ISSUE THREAD

**Issue by slightlytyler** [ljharb/qs#218]
So I love that this feature was added but don't love that it doesn't work for SSR applications!
 ```js
qs.parse('?first=10', {
  ignoreQueryPrefix: true,
});
```
is producing `{ first: "10" }` in the browser but `{ '?first': '10' }` in node.

**Comment by ljharb** [comment]
Hm, that doesn't seem right. Are you sure you're using the same version of `qs` in both?

**Comment by slightlytyler** [comment]
@ljharb its the same app that runs on the server and client, same codebase

**Comment by slightlytyler** [comment]
I'll try to produce a minimal example as it's almost certainly a characteristic of my env

**Comment by ljharb** [comment]
Thanks, with a repro case I can fix it, but the automated CI tests run in `node`, so if anything I'd expect to see node work and the browser not.

**Comment by slightlytyler** [comment]
Don't wtf happened but in the middle of debugging (`require('qs/package.json')` to compare) it started working. Guessing some weird issue with dependencies? I have no idea. No fix needed.

**Comment by ljharb** [comment]
No worries, glad it's working!
