### ISSUE TITLE
Test node 0.6 or update engines

### ISSUE THREAD

**Issue by AndersDJohnson** [ljharb/qs#220]
This module claims to support node v0.6: https://github.com/ljharb/qs/blob/d66ac175bbf8afa44b41c2c85b04ae00bac7c916/package.json#L23

But the lowest version it tests is v0.8: https://github.com/ljharb/qs/blob/d66ac175bbf8afa44b41c2c85b04ae00bac7c916/.travis.yml#L15

We should either update it to test v0.6 also, or update its engines to v0.8 minimum.

**Comment by ljharb** [comment]
We test [down to 0.4](https://github.com/ljharb/qs/blob/d66ac175bbf8afa44b41c2c85b04ae00bac7c916/.travis.yml#L156-L159), but there's issues with npm compatibility.

"engines" is both purely advisory, and is tied to support, not to "things we automated-test on" - we also support Firefox and IE and Chrome and Safari, but don't run automated tests on any of those.

**Comment by AndersDJohnson** [comment]
Ah sorry @ljgarb, I didn't see that matrix in the travis file before.

**Comment by ljharb** [comment]
I've fixed the issue with 0.6 in a80052d1ec864f74eb65a0dcf0f881924b9b91a0 and removed it from allowed failures in 489f2f855ea1fa3be9f24300b0cf6fb26d8bbbc7.
