### ISSUE TITLE
qs.parse not taking into consideration the ? in the location.search

### ISSUE THREAD

**Issue by DStoyanoff** [ljharb/qs#231]
Hello,
I am not sure that this can be considered a bug, or it is intended, but we just noticed that when we use location.search to parse the query string, using qs.parse, the parsed object includes the ? from the query.

Example:
Let's say we have the following url: http://localhost:8080/master-games?token=devToken
We try to parse the query string to get the token, by using the following code:
`qs.parse(location.search)`

However this leads to the following object:
`{ ?token: "devToken" }`
instead of 
`{ token: "devToken" }`

It is not hard to fix it before invoking parse, but in my opinion, qs should automatically do this.

**Comment by ljharb** [comment]
This is intended - the `?` isn't technically part of the query string.

You can use the `ignoreQueryPrefix` option (documented in the readme) for `parse` if you want it to do the slice for you.
