### ISSUE TITLE
Can not stringify Map or Set object.

### ISSUE THREAD

**Issue by loopArray** [ljharb/qs#232]
When I pass in a parameter type Map or Set object, can not be stringify.
```
let request: Map<string, string | number> = new Map();
request.set('id', id);
request.set('sn', sn);
... ...
qs.stringify(request)   //result: ''
```
The desired result is 
```
id=123456&sn=sn654321
```

**Comment by ljharb** [comment]
Maps can have object keys; I think you should convert it to an object first. `[...request].reduce((acc, [k, v] => ({ ...acc, [k]: v }), {})` for example.

Anything generic would treat a Map as an iterable of entries, and a Set as an iterable of values, neither of which it sounds like you want.

**Comment by loopArray** [comment]
Yes, thank you for your reply. Convert to Object seems to be the best choice.
