### ISSUE TITLE
How to parse Array of Array without index

### ISSUE THREAD

**Issue by igordeoliveirasa** [ljharb/qs#238]
When I parse: filter[order][][]=name&filter[order][][]=ASC

I would expect this:
```json
filter: {
   "order": [
      ["name", "ASC"]
   ]
}
```

But I'm receiving this:
```json
filter: {
   "order": ["name", "ASC"]
}
```

Since it's an array of array, I need to receive as the first one.

**Comment by ljharb** [comment]
I think you need an explicit index. Otherwise, `filter[order][][]=name&filter[order][][]=ASC` could just as easily be:
```js
filter: {
   "order": [
      ["name", "ASC"]
   ]
}
```
as:
```js
filter: {
   "order": [
      ["name"],
      ["ASC"]
   ]
}
```

By providing an index, you can be explicit about which nested array "name" and "ASC" belong to - without which, there's not a reasonable thing for a lib to default to.
