### ISSUE TITLE
Doesn't work in the browser - even though it's served on CDNJS

### ISSUE THREAD

**Issue by htkoca** [ljharb/qs#239]
https://cdnjs.com/libraries/qs

Console reads `qs not defined`. I assume it's because it's built for node / require? Could browser support be added? qs' deep nested parsing is very useful for both front and back end.

Edit: Seems there is provisions in the source code to detect environment already - not sure why it doesn't work. I ran it through browserify and that works, but it should work out of box.

**Comment by ljharb** [comment]
That particular build uses `Qs`, not `qs`.

However, I'd suggest not using cdnjs, and instead `npm install`ing all the libs you need, and using a bundler like browserify or webpack.

**Comment by ljharb** [comment]
Also, it's worth noting that the next major version of `qs` will be removing that custom build, and will be *only* available via CJS and a bundler.

**Comment by htkoca** [comment]
@ljharb Thanks for the help, I'll try that out. This version is good enough as the project is version locked. I don't have access to change the build environment unfortunately :(
