### ISSUE TITLE
Support for qs.parse(Array)

### ISSUE THREAD

**Issue by EdonGashi** [ljharb/qs#240]
Hi, I have a quick question/request.

I want to be able to reproduce (as close as possible) the deserialized objects without posting the form. I'm using javascript to prevent submission, and I'm getting form values via `new FormData(form).entries()` or by manually iterating `form.elements`.

I need to be able to create the final object without going through the serialization process. I noticed that 
`qs.parse({ 'a[0]': 1, 'a[1]': 2 })` works great (it returns the expected `{ a: [ 1, 2 ] }`). The mismatch starts to occur when I have duplicate keys, for which I cannot pass an object parameter. It would be great if there would be a syntax supporting arrays, something like:

```js
qs.parse([['a', 1], ['a', 2]])
// or
qs.parse([{ key: 'a', value: 1 }, { key: 'a', value: 2 }])
```

The reason why I'd like to avoid serialization is because I may have files or blobs in inputs. Any help would be appreciated. Thanks!

**Comment by EdonGashi** [comment]
Forked dist script and added this, in case anyone needs it:

```
if (str instanceof Array) {
    for (let i = 0; i < str.length; ++i) {
        let key = str[i].key;
        let newObj = parseKeys(key, str[i].value, options);
        obj = utils.merge(obj, newObj, options);
    }
} else {
  ... // default behavior
}
```

**Comment by ljharb** [comment]
Heads up; instanceof is hugely unreliable, especially with arrays - you want `Array.isArray`.

Separately, an hour is a bit fast to warrant forking something.

I’m still not sure what you’re asking for - if you have an array of entries, you’d want to convert that to an object *before* passing it into `qs`.

**Comment by EdonGashi** [comment]
Thanks for the suggestions. 

Passing an object does not work when I have duplicate keys.
`qs.parse({ 'a': 2, 'a': 3 })` <- this won't work. I cannot convert them to a string because `a` may be a file.

**Comment by ljharb** [comment]
Yes, i understand that - that means your code that converts the array of entries to an object has to account for a repeated key (presumably by converting the value into an array, and pushing into it) - but this is an assumption that is far too specific and subjective to live in `as` itself.

**Comment by EdonGashi** [comment]
In some cases such as the one below you have to push in a nested array (the names are not predictable, trying to get this working for any form), this would require rewriting the object merging logic:

```
qs.parse([{key:'a[0][]',value:1},{key:'a[0][]',value:2},{key:'a[0][]',value:3}])
// { a: [ [ 1, 2, 3 ] ] }
```

since qs will be used in the server I was looking to mirror the behavior by reusing the same code from the client. I agree it's very specific that is why I closed the issue. Thank you!

**Comment by EdonGashi** [comment]
I created a `mergeArray` function for this job. `parseKeys` is the only dependency which I can't import from qs. Any idea how to reuse that code without duplicating it locally?
