### ISSUE TITLE
addQueryPrefix is non working

### ISSUE THREAD

**Issue by daveferrara1** [ljharb/qs#243]
Version: 6.3.2

```js
import qs from 'qs';

  let url = qs.stringify({
      param: 'one',
      param_two: 'two'
    }, { addQueryPrefix: true,  encode: false });
```

I don't seem to get a query param prefix. With or without the encoding: false is non-working.

**Comment by ljharb** [comment]
What version of `qs` do you have installed?

**Comment by daveferrara1** [comment]
6.3.2

**Comment by ljharb** [comment]
As I'm sure you discovered, that feature was [added in v6.5.0](https://github.com/ljharb/qs/blob/master/CHANGELOG.md#650)

**Comment by daveferrara1** [comment]
Yep. You got me on course. Thanks. Works in newest version of course.
