### ISSUE TITLE
Add usage way for browser projects without require

### ISSUE THREAD

**Issue by maximzasorin** [ljharb/qs#244]
For example with unpkg.com:

```HTML
<script src="https://unpkg.com/qs/dist/qs.js"></script>
<script>
Qs.parse(location.search.substring(1));
</script>
```

**Comment by ljharb** [comment]
No thanks. Every JS project should only be consumable via npm and a build process; eg browserify or webpack, otherwise you can’t make use of modules.

There’s https://wzrd.in if you’re stuck on legacy architecture.

**Comment by fritx** [comment]
@ljharb I was +1 on your view, so my library vue-at, vue-threejs were all released just in commonjs.

However, these days I changed my mind:

With a umd / unpkg.com bundle, I'm able to make up a codepen demo with no required "architecture" like webpack or browserify.

I've just published vue-threejs in umd mode along with commonjs.

Here's some of my fresh demos, benefit from umd / unpkg.com mode:

Three.js with physical effects writen in Vue
https://codepen.io/fritx/project/editor/AoLRoy

Spaceship and ocean animated in Vue
https://codepen.io/fritx/pen/KJMprm

<img width="240" src="https://user-images.githubusercontent.com/6647633/51877861-9dc63000-23a8-11e9-86e8-cd52eda92eef.png">

ref: https://github.com/fritx/vue-threejs/issues/8#issuecomment-457895468

**Comment by fritx** [comment]
```html
<script src="https://unpkg.com/qss"></script>
```

For now I switch to [qss](https://github.com/lukeed/qss/issues/1) which supports umd

**Comment by ljharb** [comment]
I will definitely agree that "codepen"-style demos is a valid use case.

Note that qs already has one of these, and always has: https://unpkg.com/qs@6.6.0/dist/qs.js but i'm going to remove it for v7.

**Comment by ljharb** [comment]
What tools look at that field? It’s not good for the ecosystem to just litter package.json with random fields.

**Comment by fritx** [comment]
@ljharb it works, I just saw other people using that field, and I tried it in vue-threejs, and then https://unpkg.com just could link to that file automatically.
