### ISSUE TITLE
need some help about array

### ISSUE THREAD

**Issue by hasbug** [ljharb/qs#245]
use qs.stringify() can get
```javascript
img[0]:1
img[1]:2
img[2]:42
payNo:15006036653305145
score:4.5
content:nice try
```

but，we need the code lick jQuery ajax
```Javascript
img[]:1
img[]:2
img[]:42
payNo:15006036653305145
score:4.5
content:nice try
```

How to do it？

**Comment by ljharb** [comment]
I'm not sure what format that data is in. Can you provide actual JS code that uses `qs.stringify`, its string output, and your desired string output?

**Comment by hasbug** [comment]
raw data：
```javascript
{
  img[1,2,42],
 payNo:"15006036653305145"
 score:4.5,
content:"nice try"
}
```
output(Form Data):
```javascript
payNo=15006036653305145&score=4.5&content=nice%20try&img%5B0%5D=1&img%5B1%5D=2&img%5B2%5D=42
```

Java developer  need：
```javascript
payNo=15006036653305145&score=4.5&content=nice%20try&img=1&img=2&img=42
```


It's a bit similar to jQuery Ajax  [traditional: true,]

**Comment by ljharb** [comment]
In that case, you're trying to omit the encoded `[]` on `img`?

In that case, use the `arrayFormat: "repeat"` [stringify option](https://github.com/ljharb/qs#stringifying).
