### ISSUE TITLE
Nested object keys are surrounded by brackets when parsed

### ISSUE THREAD

**Issue by SlaunchaMan** [ljharb/qs#247]
Hi there,

Consider the following object:

```
{
	filters: [{
		code: 'customer',
		type: 'hierarchical',
		options: [{
			name: "ACME",
			value: "ACME",
			options: [{
				id: "0000123",
				value: "Wile E. Coyote"
			}]
		}]
	}]
}
```

Running this through `qs.stringify()` with `encodeValuesOnly` set to `true` I get this:

```
'filters[0][code]=customer&filters[0][type]=hierarchical&filters[0][options][0][name]=ACME&filters[0][options][0][value]=ACME&filters[0][options][0][options][0][id]=0000123&filters[0][options][0][options][0][value]=Wile%20E.%20Coyote'
```

So far, so good. However, when _parsing_ this, I get the following:

```
{
	filters: [{
		code: "customer",
		type: "hierarchical",
		options: [{
			name: "ACME",
			value: "ACME",
			options: [{
				[id]: "0000123",
				[value]: "Wile E. Coyote"
			}]
		}]
	}]
}
```

As you can see, the `id` and `value` keys of the lowest-level item become `[id]` and `[value]`. Is there a set of options I can use to encode this type of object with multiple nested levels?

**Comment by ljharb** [comment]
There's a depth option on "parse"; it defaults to 5. You can pass `{ depth: Infinity }` and that should recurse all the way down.

**Comment by SlaunchaMan** [comment]
That works, thank you!
