### ISSUE TITLE
Support option parse to array instead of object for array encoding url

### ISSUE THREAD

**Issue by tangkhaiphuong** [ljharb/qs#248]
I use qs.parse to parse string below

`[0].id=999999&[0].number=0&[0].type=PropertyPicture&[1].id=999999&[1].number=1&[1].type=PropertyPicture&[2].id=10000&[2].number=0&[2].type=PropertyPicture`

And result is object
```
{
 "1": {
  "id": "999999",
  "number": "0",
  "type": "PropertyPicture"
 },
 "2": {
  "id": "999999",
  "number": "1",
  "type": "PropertyPicture"
 }
}
```

So please support object to parse and output array instead of object

```
[
 {
  "id": "999999",
  "number": "0",
  "type": "PropertyPicture"
 },
 {
  "id": "999999",
  "number": "1",
  "type": "PropertyPicture"
 }
]
```

**Comment by ljharb** [comment]
A key of `[0].id=999999&[0].number` seems like it's nonstandard; query strings *are* objects, conceptually, not arrays.

Try parsing `a[0].id=999999&a[0].number=0&a[0].type=PropertyPicture&a[1].id=999999&a[1].number=1&a[1].type=PropertyPicture&a[2].id=10000&a[2].number=0&a[2].type=PropertyPicture` instead?
