### ISSUE TITLE
Allow usage via CDN

### ISSUE THREAD

**Issue by franktopel** [ljharb/qs#251]
That is, create a global Object like say `qs` when loading via https://cdnjs.cloudflare.com/ajax/libs/qs/6.5.1/qs.min.js or other CDN. I know you're stongly opinionated on that but it wouldn' t be too hard to create a `qs.global.js` build and help developers 'stuck in a legacy'  architecture.

**Comment by ljharb** [comment]
https://github.com/ljharb/qs/blob/master/dist/qs.js already does that; it sets a `Qs` global.

However, that dist file will be removed in v7 (see #129).
