### ISSUE TITLE
Parse includes the '?' char

### ISSUE THREAD

**Issue by carpben** [ljharb/qs#253]
I think that the library is often used for parsing the url search string to a JS object. When using the parse function includes the '?' from the begining of the query in the first key. For example, 
{?country: "Canada"}. Perhaps it can be useful to remove the '?' char from the beginning of the string.

**Comment by ljharb** [comment]
This is by design; you can use `window.location.search.slice(1)` or the `ignoreQueryPrefix` parse option.
