### ISSUE TITLE
Does qs.parse have a callback function?

### ISSUE THREAD

**Issue by jamieYou** [ljharb/qs#255]
I want to keep the numbers
```
const query = qs.parse('id=1&bool=true') // { id: '1',  bool:'true'  }

JSON.parse(JSON.stringify(query), (key, value) => {
      try {
        return eval(value)
      } catch (err) {
        return value
      }
})

// { id: 1,  bool: true  }
```
Does 'qs.parse' provide similar functionality?

**Comment by ljharb** [comment]
JSON.parse takes a reviver; qs.parse doesn’t. However, it does have a few options that would let you keep the numbers.

https://github.com/ljharb/qs/issues/91#issuecomment-348481496 seems like it would be helpful.
