### ISSUE TITLE
[Question] Older browsers support 

### ISSUE THREAD

**Issue by abdulhannanali** [ljharb/qs#256]
Hey there,

I want to use this module on IE5.5+ and Opera 6+ (much harder than ie6), since there's no table provided which details about the browser support, @ljharb can you help please if you have any related data and what version target if any you have in mind. Thanks a lot for reading.

Kind Regards,
Hanann

**Comment by ljharb** [comment]
Although I don't think anybody still uses either of those browsers (I'd love to hear why you want to support them), qs should absolutely work in all ES3 browsers. If you find a bug in any browser I'm able to access (which includes IE 6 and Opera 11, but not older than that) then I'm happy to fix it.

**Comment by abdulhannanali** [comment]
@ljharb Because Opera 6 Matters too :wink: I am doing some browser compatibility research and it's interesting to see how far we can stretch. I will try out querystring library in older browsers. Browsers lower than Opera 6- are way too :older_man: :older_woman:  (old) , and even javascript 1.3 implementation in opera 6 lacks some of the features too. 

I am not sure if it would work though, since there are just too many things that could go wrong. Before coming here, for my tests I was making use of this well written JSON polyfill https://github.com/bestiejs/json3 but below Opera 9, it gives up and returns an empty string. Not ideal at all. So I am forced to look for other solutions.

**Comment by abdulhannanali** [comment]
For the sake of comparison, browsers such as Opera 8 are IE5.5 or lower level. So there's a good chance of a failing and I can understand why you'd not want to make this code targeted towards such a non existent audience. I guess I will hack something up for my usecase :clinking_glasses:

**Comment by ljharb** [comment]
@abdulhannanali I think it's reasonable for older browsers to require that `JSON` be polyfilled; please polyfill it as needed when testing :-)

Please do file issues for specific bugs; I'm definitely willing to fix them on a case-by-case basis.

**Comment by abdulhannanali** [comment]
@ljharb After some thinking I just ended up not testing these browsers, since they make maintenance harder without much gains. Also, the features I want to test compatibility for, are all going to return false in these ancient Egyptian era browsers anyways. Thanks a lot for your help. :)
