### ISSUE TITLE
Stringify error

### ISSUE THREAD

**Issue by Leeh91** [ljharb/qs#258]
Hi, I'm trying to stringify a json object but I got  RangeError: Maximum call stack size exceeded

this is the json object
```js
{ code: 5aeddfbbbd6b4e0dc4229453,
  customer_id: 'cus_67vnkPOCdiWZNPW5',
  items: [ { amount: 10, description: 'Produto Teste', quantity: 2 } ],
  payments: [ { payment_method: 'credit_card', credit_card: {
					installments: 1,
					statement_descriptor: "E-commerce",
					card_token: customer.default_payment
				} } ],
  shipping: 
   { description: 'Default',
     amount: 60,
     address: { _id: 5aecfea270524f47f4c6565c,
        label: 'Casa',
        isDeliveryAddress: true,
        zip_code: '12231-511',
        neighborhood: 'Vilarejo Vale das Flores',
        city: 'Florianopolis',
        street: 'Estrada Fazenda Nova Cisne',
        number: '85',
        addAddress: 'casa 64',
        country: 'Brasil' } } }
```

**Comment by ljharb** [comment]
That suggests you have a cycle - what's `customer.default_payment` look like? What happens if you remove that?

Also, what's in the `5aeddfbbbd6b4e0dc4229453` and `5aecfea270524f47f4c6565c` variables?

**Comment by Leeh91** [comment]
@ljharb  customer.default_payment stores the credit token like 

> cdr_Hk24jfWh5a76a

and 5aeddfbbbd6b4e0dc4229453, 5aecfea270524f47f4c6565c are id values for order and address

**Comment by ljharb** [comment]
@Leeh91 yes but in your snippet, they're not in quotes, which means they're variables, not strings.
