### ISSUE TITLE
Question about arrayLimit

### ISSUE THREAD

**Issue by stream7** [ljharb/qs#265]
From the readme:

> qs will also limit specifying indices in an array to a maximum index of 20. Any array members with an index of greater than 20 will instead be converted to an object with the index as the key:

Hi there! I was just wondering what's the reasoning behind this decision. Why have a limit there by default with such a surprising behaviour? (returns an object instead of an array)

**Comment by ljharb** [comment]
The decision long predates me; all I can find is https://github.com/ljharb/qs/issues/18#issuecomment-52110479.

I'm assuming the limits, and the behavior, prevent DOS attacks by crafting malicious input.

**Comment by stream7** [comment]
@ljharb I can't say I really understand the reasoning (and I read all of the history/issues), I would assume this kind of security protection belongs to a different abstraction but thanks a lot for checking and for pointing me to that discussion (I should have searched better :) ).
