### ISSUE TITLE
Feature request: Suppress treating Plus Sign as space in `qs.parse`

### ISSUE THREAD

**Issue by thomb** [ljharb/qs#266]
I'm running into a situation where the default behaviour of `utils.decode` (https://github.com/ljharb/qs/blob/master/lib/utils.js#L112) produces undesirable results.

I have an email address in a URL, like so `thomb+github@email.com`, where the plus is actually an integral part of the email address used to lookup the user. 

I understand that in the vast majority of use cases, the current behaviour would be desirable, so 
I'd like to be able to get the actual values from the URL, without any of transformations done, as an option for `decode`

**Comment by ljharb** [comment]
#221 may be related.

Have you tried handling the plus yourself with a custom decoder?

**Comment by thomb** [comment]
Yup, works fine and frankly I'd understand rather than altering the behaviour of the default `decode` it would be the preferred way to accommodate this.

I appreciate your prompt response, cheers!

**Comment by ljharb** [comment]
@thomb if you end up finding that it's not trivial to implement this - but you *do* end up implementing a complete solution - then let's reopen this at that time, and consider adding it under an option (since it would be easier for users that way). Closing for now.
