### ISSUE TITLE
Add support for tree shaking

### ISSUE THREAD

**Issue by garygreen** [ljharb/qs#270]
It would be awesome if you could only use some parts of qs rather than having to pull in the whole library.

For instance, if you want just to be able to `stringify` query strings, you can do:

```js
import { stringify } from 'qs'

stringify({ name: 'qs', stars: '3000' }); // name=qs&stars=3000
```

This would allow for tree-shaking in Webpack, Rollup and other supported libraries.

I realise qs isn't exactly a super heavyweight library, but often you only need to serialize strings and not parse, so it would cut the library size in half 👍

**Comment by ljharb** [comment]
You already can - "tree-shaking" only provides a benefit when you've failed to deep-import the things you need.

```js
const parse = require('qs/lib/parse');
const stringify = require('qs/lib/stringify');
```

This works perfectly in node, all browsers, and with all bundlers, and then there's no need for any tree-shaking to clean up after you :-)

**Comment by garygreen** [comment]
Oh awesome, thanks man, awesome library 😄

**Comment by garygreen** [comment]
I think there's still room for improvement in the code splitting. If you look at the output of just including `stringify` it'll contain various unused/unneeded utilities:

```js
compactQueue
merge
decode
isRegExp
```

Some of them are pretty large. I think the main problem is that because it's using common js modules, it can't tree shake the dependency graph well.

For example [this import](https://github.com/ljharb/qs/blob/master/lib/stringify.js#L3):

```js
var utils = require('./utils');
```

Could be this in ES6 and would tree shake more effectively:

```js
import { encode, isBuffer, assign } from './utils';
```

(importing only the required utilities for stringify)

Would you be able to a PR converting the library to ES6 modules?

**Comment by ljharb** [comment]
node doesn't support ES modules just yet, so no.

The only reason tree-shaking can't work fully for CJS is because bundlers haven't bothered to implement it - it's identically achievable.

As for "pretty large", we're talking about a file that's 5.5k [in total](https://unpkg.com/qs@6.5.2/lib/) - it's not that big, and it will gzip down to effectively nothing.

I might consider splitting up the `utils` into separate files, which would give you the benefit you need, but 99% of use cases involve both parse and stringify, so I don't think it would provide that much value.

**Comment by garygreen** [comment]
> but 99% of use cases involve both parse and stringify, so I don't think it would provide that much value

In the case of using something like axios to send data to an endpoint, or any client side ajax library, you generally only need to stringify. I haven't come across any need for parsing, yet, but can understand your reservations.

> I might consider splitting up the utils into separate files, which would give you the benefit you need

Sounds like a good idea and would achieve the same result. Maybe it's worth doing for the large utility functions like `merge` and `encode`, at least? Seems pretty straightforward, guess it would be a breaking change for people using `utils` directly but nothing that a version bump couldn't solve. Open to prs? :)

**Comment by ljharb** [comment]
Sure, that sounds great. It wouldn't need to be a breaking change; `utils` would just import and re-export them so that its API remained the same.

**Comment by Finesse** [comment]
> ```js
> const parse = require('qs/lib/parse');
> const stringify = require('qs/lib/stringify');
> ```

This approach is inconvenient if you use TypeScript. You have to add the following code to a `.d.ts` file in order to make the above code work:

```ts
declare module 'qs/lib/stringify' {
    export {stringify as default} from 'qs';
}
declare module 'qs/lib/parse' {
    export {parse as default} from 'qs';
}
```

**Comment by ljharb** [comment]
Wherever defines the types (DT, i presume) is broken unless it defines the types for every file in the package, not just the “main”. File an issue on DT to have that fixed, if so.

**Comment by Finesse** [comment]
DT defines types for the "main". That's why I can easily use
```js
import {parse, stringify} from 'qs';
```
in a TypeScript project, but have to do tricks when I use
```js
const parse = require('qs/lib/parse');
const stringify = require('qs/lib/stringify');
```

**Comment by ljharb** [comment]
@Finesse i understand - im saying that DT is broken unless it *also* defines types for the inner files in the package.

**Comment by Finesse** [comment]
Sorry, my bad.

The inner file imports are not mentioned in the readme therefore they are considered as a private (inner) API. And using a private API is a bad pattern because it may change with no warning. Meanwhile the [lodash](https://lodash.com) documentation offers users to import individual files and DT has types for the individual files. Thats why, I think, DT hasn't typed the individual files of the `qs` package.

**Comment by ljharb** [comment]
Being mentioned in the readme is irrelevant; everything reachable is public API.

**Comment by marcodpt** [comment]
I create an alternative project if you want to use es6 module, with a very simple api:
[query](https://github.com/marcodpt/query)
