### ISSUE TITLE
The requested parameter string contains a `&` character

### ISSUE THREAD

**Issue by alphawq** [ljharb/qs#272]
When I put the `&` symbol in the parameters of the post request body, I get an error result, just like the example in the image.So, what should I do in this situation?
![wechatimg10047](https://user-images.githubusercontent.com/20399793/43876522-0bf342b6-9bc8-11e8-91fa-6766b8518e27.jpeg)

**Comment by ljharb** [comment]
a POST request isn't usually a query string, so i wouldn't expect a query string library to be used with it. Can you elaborate on your use case?

**Comment by ljharb** [comment]
Happy to reopen if more info is provided.
