### ISSUE TITLE
The qs.stringify  option is support to trim string value by indicate

### ISSUE THREAD

**Issue by lihroff** [ljharb/qs#273]
The following test:
```
var qs = require('qs');
var assert = require('assert');

var str = {
    a: "  will trim ",
    b: "xxx",
    c: true,
}

const result = qs.stringify(str);
//const resultTrimed = qs.stringify(str, { tirmStringValue: true});

const except = "a=%20%20will%20trim%20&b=xxx&c=true"
//const exceptTrimed = "a=will%20trim&b=xxx&c=true"

assert.equal(result, except)    
//assert.equal(result, exceptTrimed) 

console.log("Success!")
```

Produces:
Now the assert is successful.

Consider:
In fact, I want the code I commented to successfully pass the test.
Would you like to add a similar `tirmStringValue` attribute[boolean] in the option to identify whether the value needs to be trim?

**Comment by ljharb** [comment]
I don't think that sort of option is needed; you can pass a custom decoder and trim it yourself.

**Comment by Tommy-White** [comment]
@ljharb  
Are you mean `encoder`  ? But through API doc the `encoder` accepts a function that params are a sequence of key, value... that make me can't clearly know which one is the key or value，in some cases (like:  `{a: {b: "c", d: 123, e: {f: true}}}` ). Simple, I just want my string value to be trim, and using the encoder will increase my complexity.

**Comment by ljharb** [comment]
There’s an `encodeValuesOnly` option.

**Comment by Tommy-White** [comment]
I think you may have misunderstood, look at this：
```
var qs = require('qs');
var assert = require('assert');

var str = {
    "a b": "  will trim ",
    "烫": true,
}

const result = qs.stringify(str);
const resultTrimed = qs.stringify(
    str
    /*, { tirmStringValue: true} */
    );
const except = "a%20b=will%20trim%E7%83%AB=true"

assert.equal(result, except)    

console.log("Success!")
```
I support to this assertion will be the success when I turn the comment option on.

**Comment by ljharb** [comment]
Try:
```js
const originalEncode = require('qs/lib/utils').encode;
const resultTrimmed = qs.stringify(str, {
  encodeValuesOnly: true,
  encoder: str => originalEncode (str.trim()),
});
```
