### ISSUE TITLE
Ability to get query params from entire URLs

### ISSUE THREAD

**Issue by elias6** [ljharb/qs#282]
I ran `qs.parse('http://example.com?foo=bar')` and it returned `{ 'http://example.com?foo': 'bar' }`. I think this is strange. It should just return `{ 'foo': 'bar' }`. I know I can run `slice` on the URL, but I think that should be built into this library. I can't imagine why anyone would want the current behavior.

Any thoughts?

**Comment by ljharb** [comment]
That requires a URL parser, which this library isn't. `parse` expects as input `window.location.search.slice(1)`, the most common use case.

In your case, `qs.parse(url.slice(url.lastIndexOf('?') + 1)` should work fine, as you indicated.

**Comment by elias6** [comment]
Thanks for considering my issue. I decided to use another library (https://github.com/sindresorhus/query-string/).

But I'm curious about your decision. Why wouldn't you want your library to handle entire URLs? It seems like with only a little bit of added complexity, you can turn it into something more general that handles a very common use case, without causing any serious problems, as far as I can tell. I can't imagine anyone in the world actually wanting or depending on the behavior described in my example, with the rest of the URL considered as part of one of the parameters.

**Comment by ljharb** [comment]
It's a great deal of added complexity to do it correctly.

**Comment by elias6** [comment]
Fair enough. I don't think this is worth arguing about.

**Comment by wenlittleoil** [comment]
> Thanks for considering my issue. I decided to use another library (https://github.com/sindresorhus/query-string/).
> 
> But I'm curious about your decision. Why wouldn't you want your library to handle entire URLs? It seems like with only a little bit of added complexity, you can turn it into something more general that handles a very common use case, without causing any serious problems, as far as I can tell. I can't imagine anyone in the world actually wanting or depending on the behavior described in my example, with the rest of the URL considered as part of one of the parameters.

I cannot agree more with you. it is simple, but a very common use case.
