### ISSUE TITLE
What is the difference between cdnjs and wzrd.in

### ISSUE THREAD

**Issue by acmilank22** [ljharb/qs#286]
I want to use qs in browser **without** npm, browserify, webpack or any build process.

so, What is the difference between [cdnjs](https://cdnjs.com/libraries/qs) and [wzrd.in](https://wzrd.in/standalone/qs@latest)? How to choose ?

And could I use RequireJs ?

**Comment by ljharb** [comment]
(Using anything wiout a build process within the last 10 years is deviating from best practices; a build process is required for the foreseeable future; separately, any JS consumed from anywhere but npm is not JS you want to be using)

word.in makes a browserify bundle for you on the fly; cdnjs hosts prebuilt libraries for you to hotlink. qs has a prebuilt file, but it will be going away in the next semver-major, so i wouldn’t suggest relying on it.

RequireJS is AMD, which is effectively dead; node-style CJS with a bundler is the de facto standard, for many years now.
