### ISSUE TITLE
Rename key while encoding?

### ISSUE THREAD

**Issue by aaronsky** [ljharb/qs#291]
Hey! Thanks for making this package, I'm finding it much more robust than the custom querystring constructor I wrote myself.

Here's my question: is there a way to rename a key while encoding its value? I'm wrestling with an API that expects the consumer to potentially provide `limit?: number` and `limit?: { // ... }` on some object, potentially at the same time. It's weird and frustrating, since I can't have two members with the same key on the query object. However, when expressed in the querystring `limit=20&limit[apps]=30`, it's technically valid. One way I'm getting around this is to name the object-typed `limit` key `limitField` to maintain symmetry with other parts of the query. In my custom stringify-er, I renamed the `limitField` key back to `limit` manually. Is it possible with the feature set that qs has today to perform that rename during processing?

**Comment by ljharb** [comment]
@aaronsky you closed #293; are you no longer interested in this feature?
