### ISSUE TITLE
Merge array keys into object

### ISSUE THREAD

**Issue by nicooprat** [ljharb/qs#295]
Hi there, can't find anything in docs or issues. I have this object:

```
{
  filters: {
    locations: [1,2]
  }
}
```

Here's the URL I'd like:

```
?filters={"locations":[1,2]}
```

Here's the URL I get with `qs`:

```
?locations[0]=1&locations[1]=2
```

This notation could be very long in my use case. Any idea how to achieve this? I tried a few option without success. Do I need to use a custom `encoder`? I'd rather avoid infer in `qs` behavior...

Thanks.

**Comment by nicooprat** [comment]
I got a prettier result with those methods (using Vue Router):

```js
parseQuery(query) {
  return mapValues(qs.parse(query), q => {
    try {
      JSON.parse(q) // Fails if q is a string
      return isObject(JSON.parse(q)) ? JSON.parse(q) : q
    } catch(e) {
      return q // Return string as is
    }
  })
},
stringifyQuery(query) {
  if(isEmpty(query)) return ''
  const result = qs.stringify(mapValues(query, value => {
    return isObject(value) ? JSON.stringify(value) : value
  }), {encode: false})
  return result ? ('?' + result) : ''
}
```

So I get this URL `?locations=[1,2]` instead of `?locations[0]=1&locations[1]=2`, and it correctly becomes:

```
{
  locations: [1,2]
}
```

I'm sure it can be improved, but I can't spend any more time on this for now. Any suggestion welcomed :)

**Comment by ljharb** [comment]
I think you might be looking for #276, #112, #219 ?

**Comment by nicooprat** [comment]
Looks like it gets close to what I need. Will give it a try once it's merged. I created a small fiddle to compare each `arrayFormat` option for now: https://jsfiddle.net/adcmqkt6/5/

**Comment by ljharb** [comment]
Closing for now since there's nothing actionable; happy to reopen if that's incorrect.
