### ISSUE TITLE
Standalone export should be "qs" not "Qs"?

### ISSUE THREAD

**Issue by niftylettuce** [ljharb/qs#298]
I think we should keep the API's consistent, and since Qs is not a constructor (and doesn't need invoked with `new`) it shouldn't be capitalized.

I submitted a PR to fix this (see https://github.com/ljharb/qs/pull/297).

In the meanwhile I've done `window.qs = window.Qs` as a workaround.

**Comment by ljharb** [comment]
I agree, but that would be a breaking change, and in v7 i plan to remove that file entirely, since JS should always and only be installed from npm and consumed by a bundler.
