### ISSUE TITLE
arrayFormat: 'comma' not producing suggested results

### ISSUE THREAD

**Issue by rustlemills** [ljharb/qs#299]
Testing the example code in the README.md  

qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'comma' })

#### Actual behavior

The output was 'a[0]=b&a[1]=c'
(Or more specifically 'a%5B0%5D=b&a%5B1%5D=c')

#### Expected behavior

I was expecting 'a=b,c'

#### Code to reproduce

```js
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'comma' })
```

**Comment by kpainter** [comment]
I'm also experiencing this issue. It appears that the feature is present in the Github repository but has not been published to the NPM registry.

When installing the latest package from NPM it doesn't include any of this functionality.

**Comment by ljharb** [comment]
Yes, that's correct. As you can see here: https://github.com/ljharb/qs/commit/b84acbab2c414658f15339c9e61cf9941d9d391f the functionality has not yet been released.

**Comment by zantic** [comment]
Any idea about when it will be?
