### ISSUE TITLE
parsing a URL gives incorrect results

### ISSUE THREAD

**Issue by labsvisual** [ljharb/qs#300]
## Problem
The `express` framework has a `request.originalUrl` property containing, well, the URL of the request along with all the query parameters, hashes, etc. (You also have `.url` but the output is the same.) 

When fed into `qs.parse( url );`, the resultant object has a key with extra characters (the last `/` along with the query string boundary `?`). 

## Detailed Description
`.parse( url: String|Host )` should automatically parse URLs and return a valid response. To make this more explicit and avoid any unpredictable errors, `{ parseUrl: Boolean }` can be added to the options' object. 

Consider the following snippet of code:
```javascript
const express = require( 'express' );
const qs = require( 'qs' );

const app = express();

// ---
// Set the basic middleware functions
// ---

app.get( '/', ( request, response ) => {
    response.json( qs.parse( request.originalUrl ) );
} );

app.listen( 3000 );
```

## Exact Error
Consider a URL: `http://localhost:3030/api/v1/auth?property=hello`. `qs.parse(...)` should return:
```js
{ property: 'hello' }
```

but instead the following is returned:
```js
{ '/auth?property': 'hello' }
```

In this case, the property `request.originalUrl` is `/auth?property=hello`. 

## Possible Solution
In [this](https://github.com/ljharb/qs/blob/master/lib/parse.js#L45) line, the `delimiter` is used to split the string into parts. The string `?foo=bar&one=baz` when split by using as `&` as the pivot will give `[ '?foo=bar', 'one=baz' ]`; similarly, when done on `/auth?property=hello` will just return `[ '/auth?property=hello' ]`. 

A possible solution can be the following snippet:

```javascript
// file: parse.js

// ...
var cleanStr = options.ignoreQueryPrefix ? str.replace(/^\?/, '') : str;
cleanStr = options.parseAsUrl ? utils.cleanUrl(cleanStr) : cleanStr;
var parts = cleanStr.split(options.delimiter, limit);
// ...

// file: utils.js

// https://stackoverflow.com/questions/1701898/how-to-detect-whether-a-string-is-in-url-format-using-javascript/1701911
// There are some glaring errors in this RegExp but it serves the example.
function isUrl(s) {
   var regexp = /(http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/
   return regexp.test(s);
}

function cleanUrl(str) {
  if (!isUrl(str)) return str;

  var queryStartIndex = str.lastIndexOf('?') + 1;
  return str.substring(queryStartIndex);
}
```

## Versions
| Module | Version |
|---------|---------|
| Express |   4.16.4  |
|   Node    |   11.4.0  |
|   qs         |   6.6.0   |

---

I am more than willing to write this out along with the tests and submit a PR. 😄

**Comment by ljharb** [comment]
`qs` takes a query string - not a URL. You have to split at the `?` yourself.

**Comment by labsvisual** [comment]
I thought it'd be a good addition, but that makes sense!
