### ISSUE TITLE
Parse nesting object up to 2 children deep

### ISSUE THREAD

**Issue by Lupeipei** [ljharb/qs#301]
version: 6.5.2.
when I run
```
const Qs = require('qs');

const string = 'a[b][c][d][e][f][g][h][i]=j';
console.log(Qs.parse(string));
```
expected: 
```
{ a: { b: { c: { d: { e: { f: { '[g][h][i]': 'j' } } }
```
actually, what I got is:
```
{ a: { b: { c: [Object] } } }
```
I have read the source code, the default depth is 5,  and the function parseQueryStringKeys seems no problem. I have no idea why I got the unexpected result.
Did I miss something?

**Comment by ljharb** [comment]
Looks like maybe that's the limit of `console.log`? What happens if you `console.log(Qs.parse(string).a.b.c)`?

**Comment by Lupeipei** [comment]
> Looks like maybe that's the limit of `console.log`? What happens if you `console.log(Qs.parse(string).a.b.c)`?

I got 
```
{ d: { e: { f: [Object] } } }
```
You're right! Thanks! It's the limit of `console.log`. I should think twice before I create this issue.
