### ISSUE TITLE
How to set default options for stringify?

### ISSUE THREAD

**Issue by niftylettuce** [ljharb/qs#302]
Having to repeat the options for every usage of `qs.stringify` is pretty repetitive.

It'd be great if we could override the default formatter from RFC 3986 to RFC 1738 for example when using `qs.stringify`.

Perhaps in v7 you add the ability to set defaults through instances of the class `const qs = new Qs({ ... })`?

**Comment by ljharb** [comment]
```js
const defaults = { whatever: true };
const stringifyWithDefaults = (value, opts = {}) => qs.stringify(value, { ...defaults, ...opts });
```
?

Seems a lot easier than adding statefulness to what's otherwise a set of pure functions.

**Comment by niftylettuce** [comment]
That's what I'm doing temporarily already 👍

**Comment by niftylettuce** [comment]
Probably best since there's not many options anyways to just keep these pure funcs.
