### ISSUE TITLE
The comma arrayFormat option does not work in 6.6.0.

### ISSUE THREAD

**Issue by ogenodisho** [ljharb/qs#304]
From the 6.6.0 docs:

> You may use the arrayFormat option to specify the format of the output array:
```
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'indices' })
// 'a[0]=b&a[1]=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'brackets' })
// 'a[]=b&a[]=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'repeat' })
// 'a=b&a=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'comma' })
// 'a=b,c'
```

After trying this out online: https://repl.it/repls/OnerlookedImaginativeFeed

They all work except for the last one where the `arrayFormat` is `comma`.
I am expecting `a=b,c` but I am getting `a[0]=b&a[1]=c`.

**Comment by pspi** [comment]
Looks like the code that implements 'comma' as arrayFormat is not included in the 6.6.0 release.

**Comment by ogenodisho** [comment]
> Looks like the code that implements 'comma' as arrayFormat is not included in the 6.6.0 release.

That's confusing, 6.6.0 is currently the latest release so I assumed it would have it. Oh well...

**Comment by ljharb** [comment]
When reading doc, please check the tag, not master.

**Comment by cemremengu** [comment]
Anything we can do to help for releasing this feature?

**Comment by chiefGui** [comment]
@cemremengu Use [Sindresorhus' `query-string`](https://github.com/sindresorhus/query-string#arrayformat-1).

(Sorry maintainers of qs, but since we don't have control over releasing functionalities, this is the best response to use `arrayFormat` as for now.)

**Comment by ljharb** [comment]
@chiefGui yeah, it's really not. The best response is "be patient". If it was that urgent, it wouldn't have taken almost a year and a half for someone to send a PR implementing the requested feature.

**Comment by ljharb** [comment]
v6.7.0 has been released.

**Comment by cemremengu** [comment]
Thank you for your hard work @ljbarb :pray:
