### ISSUE TITLE
Object value parsed as string

### ISSUE THREAD

**Issue by handreistoicescu** [ljharb/qs#308]
Given the following query string:

`?filter={name:'Joe'}`

When using qs.parse on it I get this:

`{ filter: "{name:'Joe'}" }`

As you can see, the value for the _filter_ property is a string, not an object, as I expected. Could there be anything that I'm missing?

**Comment by ljharb** [comment]
Query string values are only a string. If you want an object, you want `?filter[name]=Joe`.

**Comment by handreistoicescu** [comment]
Thank you for the explanation. Is this query string example based on a standard or something? I'm asking because I use a front-end library that sends requests just like I've illustrated in the previous message, and it looks to me that this way of composing query strings is totally incompatible with Express and qs.

**Comment by ljharb** [comment]
Yes, it's based on both a standard, and also the way that Rails, PHP, and node express all handle query strings.

Which library is sending values in this way (JSON-encoded, presumably)?

**Comment by ljharb** [comment]
Note that you can certainly provide a custom encoder and decoder to stringify and parse - but sending values as JSON doesn't really have any pros, and does come with some cons, so I'm not sure why it'd be the preferred method.

**Comment by handreistoicescu** [comment]
> Yes, it's based on both a standard, and also the way that Rails, PHP, and node express all handle query strings.

Thanks for the info! Would It be too rude if I asked for a link with a summary on recommendations based on that standard? I'm mostly developing front-end, and I'm not that familiar with this, but it sounds real interesting.

> 
> Which library is sending values in this way (JSON-encoded, presumably)?

It's [ra-data-simple-rest](https://github.com/marmelab/react-admin/tree/master/packages/ra-data-simple-rest). It's used by react-admin, which is fairly popular.

If you look in the ra-data-simple-rest readme file examples of using the GET_LIST verb, you'll see that query string.

**Comment by handreistoicescu** [comment]
> Note that you can certainly provide a custom encoder and decoder to stringify and parse - but sending values as JSON doesn't really have any pros, and does come with some cons, so I'm not sure why it'd be the preferred method.

Well, yes, that's how it also seemed to me, but it was just a hunch. Thanks for giving me certainty :)

**Comment by ljharb** [comment]
I won't pretend to have read or understood this in its entirety, but i believe https://tools.ietf.org/html/rfc3986 is the relevant standard.

What I *am* familiar with is how rails, php, and node express parse query strings, which is what qs is largely aligned with.

**Comment by handreistoicescu** [comment]
All clear now. I'll mark this as closed and proceed to modifying my weirdly-shaped front-end query strings.
