### ISSUE TITLE
Wrong decoding of special sequence

### ISSUE THREAD

**Issue by olessavluk** [ljharb/qs#309]
Hi,

I am trying to parse the following query:
`q=@%C2%A3$%^%` (which is created by pasting `@£$%^%` in browser URL)

**Current behavior:**
```
> qs.parse('q=@%C2%A3$%^%')
{ q: '@%C2%A3$%^%' }
```

**Expected behavior:**
```
> qs.parse('q=@%C2%A3$%^%')
{ q: '@£$%^%' }
```

Additional information:
 - it is parsed correctly when using https://github.com/sindresorhus/query-string
 - google parse such URL correctly, try `https://www.google.com/search?q=@%C2%A3$%^%`
 - GitHub fails `https://github.com/search?q=@%C2%A3$%^%`
 - wikipedia fails `https://en.wikipedia.org/@%C2%A3$%%5E%`

Is there a way to parse such url properly? (or there is some problem with sequence itself?)

**Comment by ljharb** [comment]
When I do `qs.stringify({ q: '@£$%^%' })` I get `'q=%40%C2%A3%24%25%5E%25'` (which round trips correctly).

`decodeURIComponent('%40%C2%A3%24%25%5E%25')` returns `'@£$%^%''`, but `decodeURIComponent('@%C2%A3$%^%')` throws with "URI malformed". It doesn't seem like that's actually a valid query string at all.

**Comment by ljharb** [comment]
It looks like query-string uses https://www.npmjs.com/package/decode-uri-component which markets itself as a "better" decodeURIComponent, but that seems like it means it permits invalid input.

I think you could use that in a custom decoder if you like, and it'd work?

**Comment by olessavluk** [comment]
Using custom decoder works for me, thanks!
