### ISSUE TITLE
arrayformat as comma with empty array or objects

### ISSUE THREAD

**Issue by davidlandais** [ljharb/qs#310]
```javascript
const options = {
  encode: false,
  strictNullHandling: true,
  arrayFormat: 'comma',
  allowDots: true,
  addQueryPrefix: true
};

const params = {
  foo: [],
  bar: [null],
  baz: ['abc'],
};

// with arrayFormat: 'comma'
qs.stringify(params, options);
// = ?foo=&bar=&baz=abc

// with arrayFormat: 'brackets'
// = ?bar[]&baz[]=abc
```

`stringify` will produce `?foo=&bar=&baz=abc`. But using `brackets`, `indices`, `repeat` as array format will not concat `foo` cause it's an empty array. `comma` is the only one which keep foo. Is it a bug or a conception choice ?

In `lib/stringify.js`, line 67, maybe you could test if it's an array with values ?

**Comment by ljharb** [comment]
Are you suggesting that `comma` shouldn't include `foo`, or that the other three should?

**Comment by davidlandais** [comment]
Yes, i'm suggesting that comma shouldn't include foo :) All three other does not include it and i expected comma don't too. What do you think ?

**Comment by ljharb** [comment]
That seems reasonable to me.

**Comment by davidlandais** [comment]
When i got time, i will make you a pull request

**Comment by ljharb** [comment]
@davidlandais nope, help wanted means it's up for grabs :-) a PR would be great.

**Comment by kruchone** [comment]
I would like to offer my 2c on the opposite; I believe we should _not_ strip the key out of the original object.
I am not sure `qs` should be assuming the intention of the empty array is to completely omit the query string entry _entirely_. I get that this is probably to-spec in HTTP but the reality is not all HTTP services are to-spec and this could cause problems if the intention of the caller is to actually send the blank query parameter. We are effectively stripping context out of the object when we remove the empty kv pairs.
I would argue that the caller could simply strip empty values before `stringify` even gets called if it really doesn't want them in the resulting string.

**Comment by ljharb** [comment]
@kruchone how to handle empty values seems like something that should be resolved in #226 - until then, i think it's important for all the arrayFormat options to behave the same.

**Comment by daggerjames** [comment]
It's a bug, I'll fix that later

**Comment by issuefiler** [comment]
# Suggestion

There’s _a use case where you have to convey the presence of an array, empty or not_, and I find `[null]` rather counterintuitive for that purpose. I think there should be an option to specify the way `qs` handles empty arrays.

**Comment by ljharb** [comment]
@issuefiler what is one use case for that?

**Comment by jprosevear** [comment]
> @issuefiler what is one use case for that?

An index REST api endpoint that takes filters that are query params in an 'in' style:
status=[1, 2, 3]

An empty array would filter to no elements but no query params (ie status=[] where qs would stringify as empty) would get all.
