### ISSUE TITLE
comma separated arrays not working in 6.7.0?

### ISSUE THREAD

**Issue by ericsnap** [ljharb/qs#313]
Trying to avoid using comma-separated arguments internally, but a particular API insist on comma-separated list of integers.

So, I come here looking to use the new `arrayFormat: 'comma'`. And I see #304 that says it's fixed in in `6.7.0`. But the following code generates `foo=1%C2` instead of `foo=1,2`.

```javascript
var qs = require('qs');

const stringified = qs.stringify({foo: [1,2]}, {arrayFormat: 'comma'});
console.log(stringified);
// foo=1%C2
```

what am I missing?

Yes, I was told I could use `encode: false` but that will create its own set of issues and I will have to encode everything myself.

**Comment by ljharb** [comment]
That's the correct encoding of a comma that backends should be able to decode - if it needs to be a literal comma for some reason, you can do something like:
```js
qs.stringify({foo: [1,2]}, {
  arrayFormat: 'comma',
  encoder(str, defaultEncoder, charset) {
    return str === ',' ? str : defaultEncoder(str, defaultEncoder, charset);
  }
})
```

**Comment by ericsnap** [comment]
@ljharb thanks for the quick response. I agree. I am really trying to push back on using `{foo:1,2}` for our API, but it's like talking to a wall... The more code I have to write to _make it work_, the more it should highlight that it's not a good design to start with.
Thanks for the really cool library!

**Comment by ljharb** [comment]
Backends should always bend to make frontend coding easier, because the backend is a single controlled environment, and the frontend is infinite uncontrolled environments - good luck!
