### ISSUE TITLE
why ? bug ? on qs.stringify   arrayFormat

### ISSUE THREAD

**Issue by Hello-Huxu** [ljharb/qs#314]
![image](https://user-images.githubusercontent.com/31545252/58862253-d96c6000-86e2-11e9-872d-a368a7d12bb9.png)

**Comment by Hello-Huxu** [comment]
it should be: b[]=a&b[]=b&b[]=b
Why is that

**Comment by ljharb** [comment]
it is, those are URL-encoded square brackets.

**Comment by Hello-Huxu** [comment]
> 它是，这些是URL编码的方括号。

Excuse me
Can't this problem be solved?

**Comment by ljharb** [comment]
There is no problem. Any server will decode those as `[]` properly.

If you prefer to have them look like `[ ]`, then you can pass the `encodeValuesOnly` option, for example.

**Comment by Hello-Huxu** [comment]
> There is no problem. Any server will decode those as `[]` properly.
> 
> If you prefer to have them look like `[ ]`, then you can pass the `encodeValuesOnly` option, for example.

thank you very much
I'm too careless
