### ISSUE TITLE
Just learned about URLSearchParams, how much payload size would be trimmed if URLSearchParams were used for the "heavy lifting" of qs?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ljharb/qs#319]
Looks like it covers most things
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

**Comment by ljharb** [comment]
Virtually none - see https://bundlephobia.com/result?p=urlsearchparams@0.1.1 vs https://bundlephobia.com/result?p=qs@6.7.0.

Separately, it doesn't support nested parsing like qs does, everything has to be flat - qs mirrors rails, php, express, and many others. If USP is supported in all your browsers, and that's all the functionality you need, I'd use that - but that's unlikely to be the case in my experience.

**Comment by julian-alarcon** [comment]
URLSearchParams is now used by 100% of the browsers.
https://caniuse.com/?search=urlsearchparams

Also 100% compatibility according to MDM, that includes Deno and NodeJS

https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#browser_compatibility

So, I will say that for the 95% of the cases qs is not needed any more, and it is much better and recommended to use URLSearchParams.

**Comment by ljharb** [comment]
That very page says 96%, lol.

Either way, USP can't handle nesting, and a very high percentage of cases require nesting and can't ever use USP.

**Comment by julian-alarcon** [comment]
@ljharb Internet Explorer and Opera mini are not going to support this. Those are unsupported browsers and hace less than the 0.5% percente of the browsers usage.

Those should be even removed form CanIUse, in my humble opinion

**Comment by ljharb** [comment]
Of course they won't, thus 100% isn't ever accurate without a qualifier.

**Comment by ljharb** [comment]
Regardless though, the point is that USP is not *capable* of replacing the primary purpose of qs. if all you want is USP, then you can use that, or the querystring core module.
