### ISSUE TITLE
Bloated memory on load

### ISSUE THREAD

**Issue by leungi** [ljharb/qs#320]
Hi,

I was promoting your `qs` package to another user, when he realized that upon loading `.q` files into R session, the object size may be bloated by 2-3x. 

I validated his findings with my own `.q` files.

The file size shown in RStudio Environment pane may be misleading (reflecting similar size as saved object), but inspecting object size via `object.size()` and checking memory use via Windows Resource Monitor confirmed this bloating issue.

**Comment by ljharb** [comment]
I'm not sure what R has to do with anything - this is a node package.

**Comment by leungi** [comment]
Apologies @ljharb; posted on wrong repo; closing this.

There's one ported to R, and that was where I intended to post.
