### ISSUE TITLE
allowPrototypes doesn't work correctly (Not a security problem)

### ISSUE THREAD

**Issue by kjsman** [ljharb/qs#321]
```js
qs.parse('__proto__[a]=b', {allowPrototypes:true});
({}).a // undefined
```

It allows prototypes, so it should execute it correctly.

**Comment by ljharb** [comment]
This allows overwriting of `Object.prototype` properties; `__proto__` is special and will never be treated as such. If it *did* work the way you wanted, it *would* be a security problem.

**Comment by kjsman** [comment]
Oh, I see.
> By default parameters that would overwrite properties on the object prototype are ignored,
Then, how about to change this document's expression more definitely, as
> By default parameters that would overwrite properties which are defined on the object prototype are ignored,

**Comment by kjsman** [comment]
Oops. I closed it by mistake.
Please close it if above comment doesn't make sense.

**Comment by ljharb** [comment]
Technically this is already correct, `__proto__` is just a normal data property when used dynamically.

**Comment by kjsman** [comment]
Okay, I got it.
