### ISSUE TITLE
stringify.js Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by niesk** [ljharb/qs#322]
```
`RangeError: Maximum call stack size exceeded
    at pushToArray (stringify.js:23)
    at Object../node_modules/qs/lib/stringify.js.module.exports [as stringify] (stringify.js:238)`
```

```
`var pushToArray = function (arr, valueOrArray) {
    push.apply(arr, isArray(valueOrArray) ? valueOrArray : [valueOrArray]);
};`
```
Array length exceeds 45,000

If the length of the array is smaller, no error will be reported.

Operating environment: `Google Chrome 74.0.3729.131`
Library version: `6.7.0`

**Comment by ljharb** [comment]
You're trying to stringify an array of length 45000? are you aware that query strings have a 2K limit? :-p

**Comment by niesk** [comment]
Yes, I know. But my server has set no limit on the length of the query string.

**Comment by niesk** [comment]
It's not a good design to have a single request query string too long. I've used the method of splitting data multiple requests to solve the problem.

**Comment by ljharb** [comment]
Browsers have a limit, so it’s pretty important to keep the length down.
