### ISSUE TITLE
Data of complex list type cannot be supported for post requests,how to do?

### ISSUE THREAD

**Issue by Kylelkh** [ljharb/qs#323]
`{
  "paramOne": "1",
  "paramTwo": [
    "123",
    "333"
  ]
}`

**If I have this structure, and I expect the data to look something like this, how should I parse it using qs.**
eg,
![image](https://user-images.githubusercontent.com/10898224/61470059-f4edaa80-a9b2-11e9-84d5-68c01799256b.png)

**The results I've achieved so far are as follows:**
![image](https://user-images.githubusercontent.com/10898224/61469407-b86d7f00-a9b1-11e9-9657-09204ebdc9e8.png)

**I expect no Angle brackets, just like**
![image](https://user-images.githubusercontent.com/10898224/61469819-7c86e980-a9b2-11e9-8d34-2160f2139718.png)
**But I found I couldn't find a way to do it.**

**Comment by ljharb** [comment]
Since it's an array, the `[]` is actually ideal and explicit; but you can set the `arrayFormat` option to `repeat` to get that behavior.
