### ISSUE TITLE
comma and bracket combined?

### ISSUE THREAD

**Issue by RobMayer** [ljharb/qs#327]
```
parse("foo[]=1,2,3&foo[]=4,5,6", {comma: true})
/*
expected { foo: [ [ 1, 2, 3 ], [4, 5, 6] ] }
received { foo: [ 1, 2, 3, 4, 5, 6 ] }

*/
```

uncertain if this is intentional or not

**Comment by ljharb** [comment]
This actually does seem like a bug, thanks.

**Comment by RobMayer** [comment]
Glad to be of service.
For what it's worth, it works as intended if you force the index in the url string:
?a[0]=1,2,3&a[1]=4,5,6
