### ISSUE TITLE
Stringify with arrayFormat: comma, wrongfully encode comma in return

### ISSUE THREAD

**Issue by Om4ar** [ljharb/qs#337]
wrong result with stringifying 

```qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'comma' })```
return ```a=b%2Cc```

when it should return ```a=b,c```

because parsing ```,```  as reserved character per RFC 3986 should split the array if we used a parser with```comma: true``` option 
and ```%2C```  (percent encoded comma) should be treated normally as text character
 
related to : #336 pr

**Comment by ljharb** [comment]
I believe this should be fixed with #361?

**Comment by coatesap** [comment]
This doesn't actually appear to have been fixed. The latest version still outputs `a=b%2Cc`. In fact the unit test also confirms that is the current behaviour: 
```js
st.equal(
  qs.stringify({ a: ['b', 'c', 'd'] }, { arrayFormat: 'comma' }),
  'a=b%2Cc%2Cd',
  'comma => comma'
);
```
Surely this is wrong though, as it means you can't encode values that have commas in themselves?

**Comment by ljharb** [comment]
You can, it will double-encode them i believe. A PR adding those as test cases would be appreciated.

**Comment by andredewaard** [comment]
Is there a workaround for this?

**Comment by ljharb** [comment]
@andredewaard it's not clear there's anything to be worked around. A PR with failing test cases would help to quickly result in an answer or a fix.

**Comment by ananiy** [comment]
using `{
      encode: false
    }` options to fix this

**Comment by coatesap** [comment]
I've just tested this, and it doesn't double encode them. Which means that currently you can't send value that contain commas when using commas for the `arrayFormat`.

```js
qs.stringify({ a: ['b,c', 'd,e'] }, { arrayFormat: 'comma', encode: true }) 
// output: a=b%2Cc%2Cd%2Ce
// decoded: a=b,c,d,e
```
Should this issue be re-opened or a new more-specific one started?

**Comment by ljharb** [comment]
@coatesap See #338.

**Comment by Simba14** [comment]
Hey @ljharb, what's the status of the draft #338? Would be great to have it merged in 👌

**Comment by ljharb** [comment]
@Simba14 i left a review comment in november 2019, and the OP hasn't responded since. If you'd like to help, please feel free to comment on that PR with a link to an updated branch/commit (please do not open a new PR).
