### ISSUE TITLE
[Question] How to Parse Search String containing a Redirect URL with Multiple Query Arguments

### ISSUE THREAD

**Issue by thedanchez** [ljharb/qs#341]
Given the following: 

```
const queryString = '?t=myToken123&s=314&redirect=/path/to/page?arg1=foo&arg2=bar'
const result = qs.parse(queryString, {ignoreQueryPrefix: true})
```

Which parsing option do I have to supply such that I'm able to get the following outcome?

```
result.t = 'myToken123'
result.s = '314'
result.redirect = '/path/to/page?arg1=foo&arg2=bar
```

Currently, for the redirect case, I am receiving the following `/path/to/page?arg1=foo` that is missing `arg2=bar` which is undesirable.

**Comment by ljharb** [comment]
Your `result.redirect` has to be URL-encoded (the `&`, specifically).

The issue is that you manually constructed your query string in the first place. You should be using qs.stringify on `result` on the sending side, *never* manually constructing the query string.

**Comment by thedanchez** [comment]
Sorry, I don't fully understand your last statement unfortunately. Yeah, the reason it's manually constructed is because I'm using `qs` inside of a utility function that I'm writing test cases for and I ran into this use-case that I'm now trying to get working.

So are you saying that `queryString` needs to be URL encoded before being fed into `qs.parse()` in order to get the outcome I'm expecting?

**Comment by ljharb** [comment]
I'm saying that it's not a valid query string if that `&` is *not* URL-encoded.
