### ISSUE TITLE
Is it possible to use comparison operators like ">=",  "<=", "<>" etc.

### ISSUE THREAD

**Issue by pie6k** [ljharb/qs#342]
Eg.

Let's say I want to parse input like `person.age>=20`

Right now result is

```js
{ 'person.age>': '20' }
```

Would be great to get output like
```js
{
  'person.age': '<=20'
}
```

or even
```js
{
  'person.age': {
    __value: 20,
    __compare: '<='
  }
}
```

I was trying to play with `encode` and `decode` options, but I couldn't find any good docs about them and I didn't really know how to start

**Comment by ljharb** [comment]
I'm not sure what you mean. If you want `person.age` to be `<= 20` then you'd do `person.age=<%3d20`, no?

**Comment by senyaak** [comment]
`person.age=%3C%3D20`
If u know the result - just use qs.stringify method to get correct query string

**Comment by ljharb** [comment]
Closing - the special characters like - must be URL-encoded if you want them treated as values instead of as delimiters.
