### ISSUE TITLE
When parsing with `comma: true`, params with a single or no value return a string rather than as an array.  Is there an option to always return an array?

### ISSUE THREAD

**Issue by TimeDropsSB** [ljharb/qs#344]
I looked at the docs and issues but I am not sure if there is an option built into qs that could do this.

Given a query string like:

```
?a=1&b=2,3&c=
```

When parsing with `comma: true`, the result is:

```js
{
  a: "1",
  b: ["2", "3"]
  c: ""
}
```

What I want is `a` and `c` to be an array format instead.  Is there an option to always return an array when parsing?

**Comment by ljharb** [comment]
Suffix the key with `[]`.

**Comment by TimeDropsSB** [comment]
Bummer.  So qs doesn't have an option and has to rely on the query string.

Guess I won't use the comma option and just do the classic string split instead.

**Comment by ljharb** [comment]
I’m not sure i understand tho. You’re saying you want everything to be an array always?

A query string item - in every spec and implementation - is only an array if it’s repeated or has a bracket suffix. qs adds the comma option, but single values remain as they always are - single values.

**Comment by TimeDropsSB** [comment]
In my use case, yes, I want everything as an array because, using the query example I mentioned, `a` and `c` do take comma-separated values.  Therefore, having keys which are all normalized to the same type - `string[]` - makes data manipulation ib the Javascript side much easier.  All of this, of course, with the necessity that none of the params are suffixed with `[]`.

Ultimately, what I was hoping was that qs had a built-in option to simply convert each one to a string array so that I don't have to do the normalizing myself.  Given your answer, I think it makes sense why qs wouldn't have a built-in method for such.

**Comment by ljharb** [comment]
You can do `[].concat(arrayOrString)` whenever you need to ensure you have an array, but yes i think you need to do that normalization yourself.
