### ISSUE TITLE
Stringifying arrays seems to encode objects

### ISSUE THREAD

**Issue by annaloukianova** [ljharb/qs#352]
I am on `qs` version 6.9.1
By default with no options added, I am expecting 
`fromDate=2020-01-15T18%3A28%3A32Z&toDate=2020-01-22T18%3A28%3A32Z&type[0]=c5d.large&type[1]=t2.medium`

However,  I get back a query string that encodes arrays with commas:
Input: 
```
 data = {
  "fromDate": "2020-01-15T18:28:32Z",
  "toDate": "2020-01-22T18:28:32Z",
  "type": [
    "c5d.large",
    "t2.medium"
  ]
}
qs.stringify(data)
```
Output:
`fromDate=2020-01-15T18%3A28%3A32Z&toDate=2020-01-22T18%3A28%3A32Z&type=c5d.large&type=t2.medium`

According to the documentation
> When arrays are stringified, by default they are given explicit indices
> You may override this by setting the indices option to false

which is not the behavior we're seeing here.

And with brackets or indices option: 
Input: 
```
qs.stringify(data, { arrayFormat: "brackets" )
// or 
qs.stringify(data, { arrayFormat: "indices" )
```
Output:
`fromDate=2020-01-15T18%3A31%3A36Z[object Object]toDate=2020-01-22T18%3A31%3A36Z[object Object]type=c5d.large[object Object]type=t2.medium`

As you can see, it looks like the `&` character is being encoded improperly, but also not in the correct array format.

Is there anything I should try to do to debug this issue?

Here is my output from `yarn list qs`:
```
├─ body-parser@1.19.0
│  └─ qs@6.7.0
├─ express@4.17.1
│  └─ qs@6.7.0
├─ qs@6.9.1
└─ request@2.88.0
   └─ qs@6.5.2
```

**Comment by annaloukianova** [comment]
My mistake.

**Comment by ljharb** [comment]
What was the issue?

**Comment by annaloukianova** [comment]
Wasn't able to reproduce it in codesandbox, then put my codesandbox code in the app and wasn't able to reproduce there, then re-checked all my imports and one of them (in another place) was for `qs from 'querystring';` - probably automatically imported. 
Sorry about that.

**Comment by ljharb** [comment]
Feel free to switch it to `qs`, and file a new issue if your problems don't all magically go away :-p
