### ISSUE TITLE
arrayFormat with unexpected behaviours when a single item is passed

### ISSUE THREAD

**Issue by AeonFr** [ljharb/qs#360]
When using the `qs.stringify` function, arrays with a single item are parsed as string.

```js
import qs from "querystring";
console.log(qs.stringify({ array: [1] }));
```

Result: `array=1`

Expected: `array[]=1`

**Example 2: With arrayFormat**

```js
import qs from "querystring";
console.log(qs.stringify({ array: [1] }, { arrayFormat: 'indices' }));
```

Result: `array=1`

Expected: `array[0]=1`

All of the other arrayFormat options produce the same result. It would be the expected result in the case of `{ arrayFormat: 'comma' }`, but not in the other formats.

**Comment by AeonFr** [comment]
I'm also noticing other inconsistencies with what appears in the documentation:

This is the expected (what appears in the docs):

```js
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'indices' })
// 'a[0]=b&a[1]=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'brackets' })
// 'a[]=b&a[]=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'repeat' })
// 'a=b&a=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'comma' })
// 'a=b,c'
``` 

These are my results:

```js
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'indices' })
// 'a=b[object Object]a=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'brackets' })
// 'a=b[object Object]a=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'repeat' })
// 'a=b[object Object]a=c'
qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'comma' })
// 'a=b[object Object]a=c'
```

Tested in qs versions:
- `"qs": "^6.9.1",`
- `"qs": "^6.9.2",`

**Comment by AeonFr** [comment]
# I was importing the module incorrectly. Sorry about this!

**Comment by ljharb** [comment]
Indeed, `querystring` is a different package; this is `qs` :-)
