### ISSUE TITLE
Throw error on circular references

### ISSUE THREAD

**Issue by richarddd** [ljharb/qs#367]
Currently the library does not throw error when parsing circual references.

Example:

```javascript
const circular = {
   a : "value"
}
circular.a = circular
JSON.stringify(circular) //throws error
```

```javascript
const circular = {
   a : "value"
}
circular.a = circular
qs.stringify(circular) //freezes computer 😣
```

**Comment by ljharb** [comment]
Related to #31; seems like maybe we need the same treatment for stringify.

**Comment by Poyoman39** [comment]
What about a "maxDepth" option ?

**Comment by Poyoman39** [comment]
I also have an idea about an efficient solution throwing on circulars. But i've no idea about the browser scope target of qs ??? I would have used https://caniuse.com/mdn-javascript_builtins_map but it's not available in IE10 and lower

**Comment by Poyoman39** [comment]
Just to know. What is the targeted browser compatibility of qs ? I would have a solution working with JavaScript "Map" ... but it's not available in IE10 <=

**Comment by ljharb** [comment]
@Poyoman39 its much older than that, I’m afraid. Map can be shimmed (and should always be), but qs can’t rely on that being the case. However, we could build a fake Map with an array if WeakMap/Map isn’t available

**Comment by Poyoman39** [comment]
Ok i did a throw / Map solution (second PR) . I wanted to use Map for performance reasons. But maybe it's a bit of overOptiomisation ? Since querystrings does not contains that much keys ??? It would be possible to do it with a simple array ... les performant, but without requiring a Shim ?

What do you think ?

**Comment by Poyoman39** [comment]
Ok last PR, this time with array way :D https://github.com/ljharb/qs/pull/395

We have some choice for this one issue :D

**Comment by ljharb** [comment]
Ok please stop creating extra PRs tho - each PR is a permanent ref on the repo, so how i have 3 PRs to keep in sync :-)

**Comment by Poyoman39** [comment]
Ok sry for this ^^ Do you want i close some of them ?

**Comment by ljharb** [comment]
No, please leave them all open - whatever solution we go with, I’ll update all three PRs to have it as part of landing.
