### ISSUE TITLE
type argument missing in encoder

### ISSUE THREAD

**Issue by gomcodoctor** [ljharb/qs#368]
type argument is not passed when invoking encoder

``            return encoder && !encodeValuesOnly ? encoder(prefix, defaults.encoder, charset) : prefix;
``

**Comment by ljharb** [comment]
What version of qs are you using? That functionality's been in since v6.9.1 https://github.com/ljharb/qs/commit/7f216eef99cb9eb0ebb3714411a044174c1448cd

**Comment by gomcodoctor** [comment]
thanks.. resolved.. i think same thing can be applied on formatter
