### ISSUE TITLE
TypeError: utils.maybeMap is not a function

### ISSUE THREAD

**Issue by anhtran** [ljharb/qs#369]
Version: 6.9.4

`const x = qs.parse('a=b&c=d')`

It's normal in 6.8.x

**Comment by ljharb** [comment]
It's right here on line 246: https://unpkg.com/browse/qs@6.9.4/lib/utils.js

Are you perhaps using some kind of mocking, or PnP, or anything else nonstandard?

**Comment by ljharb** [comment]
Closing for now; happy to reopen if there's something actionable.
