### ISSUE TITLE
Problem parsing 2D associated array

### ISSUE THREAD

**Issue by Amir-Mohamadi** [ljharb/qs#374]
Thanks for your great package.

We get key `21` like this: 
```
var obj1 = qs.parse('filter[21][]=899'); 

console.log(obj1) // {filter: Object {21: ["899"]}}
```
and it works perfectly.

But for keys less than 20 we have problem getting the key

```
var obj2 = qs.parse('filter[20][]=899'); 

console.log(obj2) // {filter: [["899"]]}
```

How can I fix the problem?

**Comment by ljharb** [comment]
See the arrayLimit option, described here: https://github.com/ljharb/qs#parsing-arrays
