### ISSUE TITLE
when array is empty,outputs should be empty

### ISSUE THREAD

**Issue by newpost** [ljharb/qs#377]
```
1)qs.stringify({ a: [] }, { indices: false, arrayFormat: "comma" }) // output is a=
2)qs.stringify({ a: [] }, { indices: false }) // output is  empty
```
I want the first case to be empty as well

**Comment by ljharb** [comment]
`indices: false` is equivalent to `arrayFormat: 'repeat'`.

This seems like it's covered in tests added in #350, which was merged a few weeks after this was filed, but has not yet been released.
