### ISSUE TITLE
+ is removed from parsed string

### ISSUE THREAD

**Issue by resting** [ljharb/qs#379]
Is there anyway to retain the `+` as is? Like by changing the format type?

Eg: `value=abc+efg` after `.parse`

Result: `{values: abc efg}`

Expected: `{value: abc+efg}`

Currently, I'm replacing all `spaces` with `+`.

**Comment by ljharb** [comment]
Yes; see https://github.com/ljharb/qs#rfc-3986-and-rfc-1738-space-encoding - you can set the format to `RFC1738` and it should retain them.

**Comment by aleph-naught2tog** [comment]
@ljharb `format` is for `stringify`, not `parse`, unless I am misunderstanding. Is there a way to fix this on _parse_?

**Comment by ljharb** [comment]
I would assume if the + is url-encoded, it would parse it as expected?

**Comment by ljharb** [comment]
Indeed, `qs.parse('value=abc%2Befg')` yields `{ value: 'abc+efg' }` as expected.
