### ISSUE TITLE
ECMAScript module (ESM) bundle support

### ISSUE THREAD

**Issue by LoganDupont** [ljharb/qs#381]
Currently using qs in an Angular version 10+ application gives the following build warning:
```
WARNING in [filename] depends on 'xlsx'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Starting with Angular 10 the Angular CLI now provide warnings for CommonJS modules. Read more about it here:
https://blog.angular.io/version-10-of-angular-now-available-78960babd41

> When you use a dependency that is packaged with CommonJS, it can result in larger slower applications.
> Starting with version 10, we now warn you when your build pulls in one of these bundles. If you’ve started seeing these warnings for your dependencies, let your dependency know that you’d prefer an ECMAScript module (ESM) bundle.

And here:
https://angular.io/guide/build#configuring-commonjs-dependencies

> It is recommended that you avoid depending on CommonJS modules in your Angular applications. Depending on CommonJS modules can prevent bundlers and minifiers from optimizing your application, which results in larger bundle sizes. Instead, it is recommended that you use ECMAScript modules in your entire application. For more information, see How CommonJS is making your bundles larger

Is it possible to add ESM support?

**Comment by ljharb** [comment]
The vast majority of published JS on the planet is in CJS; whether that warning is correct or not, that's simply going to be noisy for _ever_.

Any ESM support we added would a) require adding the "exports" field first, which is likely to be a breaking change, and b) would just be a wrapper around the CJS files, and thus would probably not prevent the warning anyways.

That recommendation, I'm afraid, is frankly unrealistic and unlikely to ever be possible to achieve.

See also, #270.
