### ISSUE TITLE
Need Help To build object with some Brackets and Braces

### ISSUE THREAD

**Issue by jean-Box** [ljharb/qs#382]
In my project I use request lib and i would like to use [qsStringifyOptions ](https://github.com/request/request#requestoptions-callback) for query parametre but it's to much complicated in my case :/

In their documentation they link your module to use qsStringifyOptions

I would like to have this URL 

`http://127.0.0.1:80/endpoint?foo=bar[baz:3]&aaa=[{baa:X,caa:XX,daa:[{eaa:Z,faa:ZZ}]}]&data[B]=BB&data[C]=CC`
but I have this URL:
`http://127.0.0.1:80/endpoint?foo=bar[baz:3]&aaa=[%7B%22baa%22:%22X%22,%22caa%22:%22XX%22,%22daa%22:[%7B%22eaa%22:%22Z%22,%22faa%22:%22ZZ%22%7D]%7D]&data[B]=BB&data[C]=CC`

With this solution, the 'foo' attribute and data[B] and data[C] work fine but 'aaa' attribut not at all : 

```
{ // some standar param URI, methode ...
    useQuerystring: false,
    qsStringifyOptions : {encodeValuesOnly: true, encode: false,  indices: false},
    qs : {
      foo: 'bar[baz:1]',
      aaa:'[{"baa":"X","caa":"XX","daa":[{"eaa":"Z","faa":"ZZ"}]}]',
      data: {B:'BB', C:'CC'}
    }
}
```
thank you in advance for your help and your time

**Comment by ljharb** [comment]
Note that `request` is deprecated.

I can't speak to how another library uses `qs`.

I'm a b it confused tho; you have `aaa:` when you want `aaa=`. Equals signs, not colons, separate keys and values.

**Comment by jean-Box** [comment]
I'm asking for your help because request uses your lib to send query params in a url.
it is an error on the ":" which you speak about, I have to edit to put an equal
but I understand if you can't help me

**Comment by ljharb** [comment]
If I run this:
```js
qs.stringify({
      foo: 'bar[baz:1]',
      aaa:'[{"baa":"X","caa":"XX","daa":[{"eaa":"Z","faa":"ZZ"}]}]',
      data: {B:'BB', C:'CC'}
    }, {encodeValuesOnly: true, encode: false,  indices: false})
```
I get this: `foo=bar[baz:1]&aaa=[{"baa":"X","caa":"XX","daa":[{"eaa":"Z","faa":"ZZ"}]}]&data[B]=BB&data[C]=CC`.

**Comment by jean-Box** [comment]
thank's for you help, we have send request with this encoded brackets ans braces, and it work ! i d'ont understand why ...
