### ISSUE TITLE
Stringify does not work with hyphen.

### ISSUE THREAD

**Issue by therpobinski** [ljharb/qs#383]
Hi, hope you can help me, I am instantiating `axios` to make a request to an external `API`.
The problem is that when I use parameters I have to convert them with `qs.tringify` and these parameters are separated by hyphens. This returns an error to me: `TypeError: Converting circular structure to JSON`.
When I remove the hyphens it doesn't cause the problem, but in my case it is necessary to send the parameter with the intermediate hyphens for the parameter to be recognized.
This is a snippet of my code.
![imagen](https://user-images.githubusercontent.com/57117401/93269902-94ecc280-f775-11ea-8a1b-15ec65444349.png)

**Comment by ljharb** [comment]
Which hyphens? This snippet doesn't share what `params` is.

**Comment by therpobinski** [comment]
In the `access-token `parameter there is a `-`, which `hyphens` interferes with `stringify`. But removing the `-` leaves no problem. The conflict is that in my case it is mandatory to send an `access token` with the `-`.

**Comment by therpobinski** [comment]
For whatever reason, simply restarting my server fixed everything. Sorry to disturb you. I already closed this case. Thank you!
