### ISSUE TITLE
Qs parses the ? in the URL as part of its first key

### ISSUE THREAD

**Issue by JuanGaray93** [ljharb/qs#384]
I wrote a simple Jest test in case you want to try it out.

```js
import qs from "qs";

describe("Formatting URL location", () => {
  const token = "?token=l3375934k154w350m3";
  it("returns object with value of token when passed a querystring with a token", () => {
    expect(qs.parse(token).token).toEqual("l3375934k154w350m3");
  });
});

```

Upon inspection, the object returned by qs is `{ "token?":  "l3375934k154w350m3" }`.
This code used to work just fine before so it must have broken at some time in this last year.

**Comment by JuanGaray93** [comment]
As far as I can see, now a second param saying `{ ignoreQueryPrefix: true }` is required. This is not reflected in the docs so I had to go into the tests of the source code to figure out my issue.

**Comment by ljharb** [comment]
`qs` parses the query string; the `?` isn't part of the query string, it's the delimiter that marks the beginning of it. This has never changed in the lifetime of qs as far as I'm aware (also, I'd expect `{ "?token": "l3375934k154w350m3" }`, not `token?`)

The docs discuss this, grep for "To bypass the leading question mark, use ignoreQueryPrefix:", and every other example omits the leading `?`.

**Comment by JuanGaray93** [comment]
I honestly can't tell what happened but the code that I had to fix bc of this didn't have any tests so I  assume it was buggy all along. Thanks for your time

**Comment by ljharb** [comment]
No problem! I think you’re probably right.
