### ISSUE TITLE
Maximum call stack size exceeded while using arrayFormat: 'comma' and allowDots: true

### ISSUE THREAD

**Issue by yukipastelcat** [ljharb/qs#385]
I'm trying to use qs as default query param serializer for axios module like this:
```js
import qs from 'qs'

export default ({ $axios }) => {
  $axios.defaults.paramsSerializer = (params) => {
    const asPOJO = JSON.parse(JSON.stringify(params)) // I made this to ensure that I'm stringifying POJOs, non-Observables
    return qs.stringify(asPOJO, {
      arrayFormat: 'comma',
      allowDots: true,
      encode: true
    })
  }
}
```

However I'm getting "Maximum call stack size exceeded" error while trying to stringify this objects:
```js
{
  filters: {
    collectionIds: [],
    startDate: '2020-10-21T21:00:00.000Z',
    endDate: '2020-10-22T20:59:59.999Z',
    activitiesIds: []
  },
  page: 1,
  pageSize: 4
}
```

and

```js
{
  filters: {
    collectionIds: [],
    durationMin: 1,
    durationMax: 21,
    activitiesIds: []
  },
  page: 1,
  pageSize: 15
}
```

Call stack:
![image](https://user-images.githubusercontent.com/19402107/96899474-a1151f80-1499-11eb-9289-fdbbcf55337a.png)

If I'm changing arrayFormat to 'indices' or any other option (non 'comma'), it works just fine.

[Here](https://github.com/yukipastelcat/qs-issue-array-comma-allow-dots-reproduction) is the repository with reproduction of this issue.

**Comment by ljharb** [comment]
This is what I get locally:
```js
qs.stringify({
  filters: {
    collectionIds: [],
    durationMin: 1,
    durationMax: 21,
    activitiesIds: []
  },
  page: 1,
  pageSize: 15
}, {
  arrayFormat: 'comma',
  allowDots: true,
  encode: true
}) === 'filters.durationMin=1&filters.durationMax=21&page=1&pageSize=15'
```

I've cloned your repro repo. `npm start` fails until I run `nuxt build`, but then when it works and I load the URL, I see the issue - but the stack trace doesn't come from qs, it comes from `node_modules/@nuxt/devalue/dist/devalue.cjs.js`. In other words, this seems like a nuxt issue, not a qs issue - perhaps nuxt doesn't support query strings encoded with the "comma" option?

**Comment by yukipastelcat** [comment]
> This is what I get locally:
> 
> ```js
> qs.stringify({
>   filters: {
>     collectionIds: [],
>     durationMin: 1,
>     durationMax: 21,
>     activitiesIds: []
>   },
>   page: 1,
>   pageSize: 15
> }, {
>   arrayFormat: 'comma',
>   allowDots: true,
>   encode: true
> }) === 'filters.durationMin=1&filters.durationMax=21&page=1&pageSize=15'
> ```
> 
> I've cloned your repro repo. `npm start` fails until I run `nuxt build`, but then when it works and I load the URL, I see the issue - but the stack trace doesn't come from qs, it comes from `node_modules/@nuxt/devalue/dist/devalue.cjs.js`. In other words, this seems like a nuxt issue, not a qs issue - perhaps nuxt doesn't support query strings encoded with the "comma" option?

Well, I've figured my problem and it was kind of dumb - I forgot to extract the data from response object in my reproduction repo, so nuxt tried to stringify axios response object instead of it's data and I was getting this error. What was happening in my main repository - server responded with 400, and in my error handler I forgot to extract response data and returned whole error object, which Nuxt obviously cannot stringify.
