### ISSUE TITLE
throw exception if encoder is undefined

### ISSUE THREAD

**Issue by zheli-1** [ljharb/qs#386]
in stringify.js if typeof obj is undefined. It will throw an error

**Comment by ljharb** [comment]
```sh
> qs.stringify(undefined)
''
```

Can you elaborate? It seems to work fine for me.

**Comment by ljharb** [comment]
```js
> qs.stringify(undefined)
''
> qs.stringify(undefined, { encoder: undefined })
''
```

Can you elaborate?

**Comment by zheli-1** [comment]
Hi, thanks for the quick response. it's my mistake

I was referring to the following code:
    if (typeof obj === 'string' || typeof obj === 'number' || typeof obj === 'boolean' || utils.isBuffer(obj)) {
        if (encoder) {
            var keyValue = encodeValuesOnly ? prefix : encoder(prefix);
            return [formatter(keyValue) + '=' + formatter(encoder(obj))];
        }
        return [formatter(prefix) + '=' + formatter(String(obj))];
    }

my script accidentally deleted the following two lines which did the checking for undefined. I reverted the file it works all right now.

**Comment by ljharb** [comment]
The implication that you're using a script you wrote yourself (as opposed to a transpiler/minifier) to transform code is troubling; i'd suggest not doing that. Glad you figured it out :-)
