### ISSUE TITLE
how to set default option at stringify?? e.g.: `{ indices: false }`

### ISSUE THREAD

**Issue by kimkyeseung** [ljharb/qs#392]
I want use qs.stringify() with `{ indices: false }` option with every call.

is it available? how can I do?

**Comment by ljharb** [comment]
```js
var stringifyNoIndices = (v, o = {}) => qs.stringify(v, { indices: false, ...o });
```

**Comment by kimkyeseung** [comment]
thanks a lot.. how about this??

`qs.stringify = (v, o = {}) => qs.stringify(v, { indices: false, ...o });`

not recommend??

**Comment by ljharb** [comment]
I would not recommend that, as that would break anything else that depended on `qs`. Don't mutate things you don't own.

**Comment by kimkyeseung** [comment]
okay..thank you very much..  and is that the only way to implement what I want? right??

**Comment by ljharb** [comment]
Your only options are:
 - mutate `qs`, and break anything else that uses it
 - make a wrapper function
 - explicitly use `indices: false` at every callsite
 
 I suggest option 2 or 3.

**Comment by kimkyeseung** [comment]
clean! I'm using option 3
