### ISSUE TITLE
error in nested arrays

### ISSUE THREAD

**Issue by chumager** [ljharb/qs#397]
Hi, I've this query string:
```js
let search = "filter%5Bref%5D=&filter%5Bname%5D=&filter%5Btype%5D=&filter%5Barea%5D=&filter%5Bstatus%5D%5B0%5D=Registro&filter%5Bstatus%5D%5B1%5D=En%20Evaluaci%C3%B3n&filter%5Bresponsable%5D=&filter%5Bversion%5D=&filter%5BcreationDate%5D="

decodeURI(search);
```
filter[ref]=&filter[name]=&filter[type]=&filter[area]=&filter[status][0]=Registro&filter[status][1]=En Evaluación&filter[responsable]=&filter[version]=&filter[creationDate]=

when use qs.parse
filter.status y defined as object.
```js
qs.parse(search, {arrayLimit: 0});
```
```json
{
  "filter": {
    "ref": "",
    "name": "",
    "type": "",
    "area": "",
    "status": {
      "0": "Registro",
      "1": "En Evaluación"
    },
    "responsable": "",
    "version": "",
    "creationDate": ""
  }
}
```
Did I miss an option or there is a bug here?

Regards.

**Comment by ljharb** [comment]
What are you expecting? That looks like exactly what the query string is encoding.

**Comment by chumager** [comment]
Hi, I expect ```filter.status``` to be an array, not an object.

the query string is generated with qs.stringify, so I expect a bijective behaviour...

Regards.

**Comment by ljharb** [comment]
Arrays have indexes, but your string has named keys.

what was the original stringify call? Generally speaking, a round trip with the same options should produce the original value, yes.

**Comment by chumager** [comment]
My array have indexes, not keys... 0 and 1, it's in the repo examples, the query string is generated with qs.stringify from an object with nested arrays.

maybe I'm not explaining myself correctly, filter is an object but filter.status is an array with 2 strings, when I stringify it, becomes  filter[status][0]=someString and filter[status][1]=someOther. When parse it, becomes 
```json5
{
  filter: {
    status: {
      0: "some",
      1: "other"
    }
  }
}
```
instead of:
```json5
{
  filter: {
    status: [
      "some",
      "other"
    ]
  }
}
```


I believe it's a bug. I've to change the options in stringify to ```{arrayFormat: "brackets"}``` and it works, but the first thing the Readme says about stringify arrays is it adds indexes to the array.

I think it could be because it's a nested array inside an object, maybe an edge condition.

Anyway it works with the option.

**Comment by ljharb** [comment]
`filter[ref]` is an object with a "ref" property.

Here's what I get:
```js
var obj = {
  filter: {
    status: [
      "some",
      "other"
    ]
  }
};
qs.stringify(obj) === 'filter%5Bstatus%5D%5B0%5D=some&filter%5Bstatus%5D%5B1%5D=other';
qs.stringify(obj, { encodeValuesOnly: true }) === 'filter[status][0]=some&filter[status][1]=other';
assert.deepEqual(qs.parse('filter[status][0]=some&filter[status][1]=other'), obj); // passes
```

What version of `qs` are you using, and are you *certain* that you're not passing any arguments to `qs.stringify` or to `qs.parse` that would explain the difference?

**Comment by chumager** [comment]
Hi, let me explain better what I do.

I've a mixin for Vue.js that sync some vars with search in the URL, so you can declare what variables you want to keep sync with the URL to have permalinks in your SPA.

In this case I've a grid who shows some data from a mongo collection with some variables like, filter, sort, per page, current page, etc...

I've a watcher for each variable to mix the query string with the changes in those variables.

There is no problem in the operation, it has a couple of years working with no problem, but now the client ask to be able to filter by several options when the structure of the collection allows it, like when you have options in a select.

So I "decode" the query string with qs, then adds the new values and add it to the url.

This is my code:
```js
import qs from "qs";
const parseQS = () => qs.parse(location.search, {ignoreQueryPrefix: true, arrayLimit: 0});
export default {
  props: {
    noQsf: {
      type: Boolean,
      default: false
    }
  },
  methods: {
    toURL(v) {
      let query = parseQS();
      let {hash} = location;
      query[v] = this[v];
      let q = qs.stringify(query, {arrayFormat: "brackets"});
      window.history.replaceState(null, "", "?" + q + hash);
    }
  },
  created() {
    //leemos los valores del query
    let toSync;
    let isObject;
    let {$toSync} = this.$data;
    if ($toSync && !this.noQsf) {
      let query = parseQS();
      if (Array.isArray($toSync)) {
        toSync = $toSync;
      } else if (typeof $toSync === "object") {
        toSync = Object.keys($toSync);
        isObject = true;
      } else {
        return;
      }
      toSync.forEach(key => {
        this.$watch(
          key,
          function (v, old) {
            if (v !== old) {
              this.toURL(key);
            }
          },
          {deep: true}
        );
        //preparamos el valor
        let {[key]: val} = query;
        if (typeof val === "undefined" && isObject && $toSync[key].default) val = $toSync[key].default;
        //cast
        if (isObject && $toSync[key].cast) val = $toSync[key].cast(val);

        this.$set(this, key, val);
      });
    }
  },
  mounted() {
    let {hash} = location;
    if (hash) {
      let a = document.createElement("a");
      a.href = hash;
      this.$nextTick().then(() => {
        setTimeout(() => {
          a.click();
        }, 500);
      });
    }
  }
};
```

And a search could be:
filter%5Bref%5D=&filter%5Bname%5D=&filter%5Btype%5D%5B0%5D=Error&filter%5Btype%5D%5B1%5D=Control%20de%20Cambio&filter%5Btype%5D%5B2%5D=Nueva%20Funcionalidad&filter%5Barea%5D=&filter%5Bstatus%5D=&filter%5Bresponsable%5D=&filter%5Bversion%5D=&filter%5BcreationDate%5D=

When I reload to keep the same state the result is an object for the arrays inside the filter, If you see now I use ```{arrayFormat: "brackets"}``` in the stringify function so the query string have no indexes, and this works, but without that the result is an object instead an array.

the qs version is 6.9.6

In your readme...
![image](https://user-images.githubusercontent.com/775491/108634240-78a52e00-7457-11eb-963d-e8f30966b0c5.png)
![image](https://user-images.githubusercontent.com/775491/108634283-abe7bd00-7457-11eb-83fd-3f179d0340a3.png)

So the stringify by default creates indices but when parsed I've the problem.

Maybe it's more clear now?

Best regards.

**Comment by ljharb** [comment]
ok so the issue is `arrayLimit: 0`, which none of those readme examples are using. This ensures you don't ever create an array, but you always create an object. (i'd also suggest using `encodeValuesOnly: true` for slightly cleaner URLs)

**Comment by chumager** [comment]
Hi, thanks a lot for your time.

Best regards.
