### ISSUE TITLE
how to resolve ' and " nest 

### ISSUE THREAD

**Issue by MelancholyAstronaut** [ljharb/qs#398]
```JavaScript
const qs = require("qs") ;
let msg = '{"name":"mike"}';
console.log(JSON.parse(msg));   //right  { name: 'mike' }
console.log(qs.parse(msg));    // not expected{ '{"name":"mike"}': '' }

```
how to convert `msg` to right standard, thank you.

**Comment by ljharb** [comment]
I’m not sure what you mean. `msg` here contains JSON, and is not a query string, so JSON.parse is the only correct thing to use with it. This library is for working with query strings.
