### ISSUE TITLE
qs.stringify Uncaught RangeError: Cyclic object value

### ISSUE THREAD

**Issue by Ockejanssen** [ljharb/qs#403]
var qs = require('qs');
var a = ['a'];
qs.stringify({x:a,y:a});

-> Uncaught RangeError: Cyclic object value

**Comment by ljharb** [comment]
This should be fixed in v6.10.1 (see #402). Can you confirm which version of `qs` you're using?

**Comment by Ockejanssen** [comment]
I tested this one with "version": "6.10.1"

**Comment by ljharb** [comment]
Thanks, I can reproduce this.

**Comment by pober** [comment]
Any updates on this?
This affects latest version if superagent module.

**Comment by ljharb** [comment]
No, I haven't come up with a fix yet. A PR in the meantime would be welcome.

**Comment by irhamputra** [comment]
Hi @ljharb, i try with umd file with qs@6.10.1, sometimes the bug is still there sometimes not 😕  should i use different version?

**Comment by ljharb** [comment]
@irhamputra i mean, it's 2021, nobody should be using UMDs for anything - but certainly if the UMD version is different than the real one, that's a bug somewhere.
