### ISSUE TITLE
Property X does not exist on type

### ISSUE THREAD

**Issue by paul-uz** [ljharb/qs#405]
I am parsing an object of query params and when accessing the various values, I'm getting the following error

"Property 'size' does not exist on type 'string | ParsedQs | string[] | ParsedQs[]'.
  Property 'size' does not exist on type 'string'.ts(2339)"

Code
```
event: {
    queryStringParameters: { 'page[size]': '2' }
}
```

```
const queryParams = qs.parse(event.queryStringParameters);
const pageSize = queryParams.page?.size; // error on this line
```

Oddly, the code works fine, just I get these error messages that are distracting me.

**Comment by ljharb** [comment]
This package does not contain types, so you'd need to file this on DefinitelyTyped.

**Comment by paul-uz** [comment]
@ljharb erm OK.

Alternatively, how can I stop those errors appearing at all?

**Comment by ljharb** [comment]
Stop using typescript?

I’m sure you could cast the return value to a different type and avoid the type error.

**Comment by paul-uz** [comment]
I'm not using typescript. But I still see the errors in VSCode.

**Comment by ljharb** [comment]
Ah, I'm not sure how to turn them off entirely, there's probably a vscode setting for it.

Otherwise, the types would have to be fixed in DefinitelyTyped.
