### ISSUE TITLE
nested json was stringified into wrong format using square brackets

### ISSUE THREAD

**Issue by t238wang** [ljharb/qs#417]
Hi, I tried to stringify this json with `qs.stringify(data, { arrayFormat: 'brackets' }` and data is `{data: {generatedTime: value}}`

the result is `data[generatedTime]=value` instead of `data=%7B%22generatedTime%22%3A%221626959827266%22%7D` does anyone know what might be wrong?

**Comment by t238wang** [comment]
when parse it back, the difference is between a json string and a json object.

**Comment by ljharb** [comment]
JSON is only ever a string; once it’s an object it’s not JSON anymore.

The encoding of the brackets and equals sign should not impact the parsing, are not required, but you can pass options to stringify if that’s what you want for some reason.
