### ISSUE TITLE
Number parsing

### ISSUE THREAD

**Issue by ngryman** [ljharb/qs#42]
Hi,

Would it be possible to get a `number` when possible, instead of a `string`?
For this query string: `?a=2`, we currently get `{ a: '2' }`. This would be awesome to have `{ a: 2 }`.

Thanks!

**Comment by jerone** [comment]
I'm wondering why the (official) JSON standard isn't followed from the beginning? 

Now I have to server-side convert all string matching the number-pattern to real numbers. Maybe add an option `strict` to comply to the standards and keep backwards compatibility.

http://json.org/
https://www.ietf.org/rfc/rfc4627.txt
http://rfc7159.net/rfc7159#rfc.section.6 
http://www.ecma-international.org/ecma-262/5.1/#sec-8.5
https://github.com/douglascrockford/JSON-js/blob/master/json.js#L294

**Comment by nabilfreeman** [comment]
Thanks @ngryman! 

I know this is quite old, but a year on, i think the decision to discard all types when stringifying is not a good idea as it is very heavy-handed. Parsing sure, but not the other way around. The `qs-numbers` package does a good job restoring this functionality.

💪

**Comment by ljharb** [comment]
@jerone because http query strings have nothing to do with json, so that'd be the wrong standard to follow?

**Comment by mehmetaydogdu** [comment]
Given the fact that parse and stringified are opposite of each other. I expect to get the same value once I stringified and then parsed a given number. But that is not the case as below. The default behaviour can be kept for compatibility but there can be an option to get number values explicitly.
const expected = {a:1};
const str = qs.stringify(expected);
const actual = qs.parse(str);
// => { a: '1' }

**Comment by ljharb** [comment]
That's not a reasonable expectation; you can't round trip through JSON.parse and JSON.stringify either.

**Comment by dragon-master-5892** [comment]
my custom number mapping here:


`// add your numbers to 'Num(**YOUR NUMBER**)' like this:   { price : 'Num(125.35)' }

const _ = require("lodash");
function deepMap(obj, iterator, context) {
    return _.transform(obj, function (result, val, key) {
        result[key] = _.isObject(val) /*&& !_.isDate(val)*/ ?
            deepMap(val, iterator, context) :
            iterator.call(context, val, key, obj);
    });
}

_.mixin({
    deepMap: deepMap
});

let myObject = {
    'manufactured_year.id': {
        '$gte': 'Num(1900.25)', '$lt': 'Num(125+(1933/2))', "depp2": {
            '$gte': '+2400', '$lt': 'Num(-45)'
        }
    }
}


let query = qs.stringify(myObject );

let q = qs.parse(query);

deepMap(q, function (v, k, o) {
    if (v) {
        if (new RegExp("(Num)+\([0-9]*\)").test(v)) {
            eval(`o[k] = ${v.replace("Num", "Number")}`);
        }
    }
});

console.log(q);

`
