### ISSUE TITLE
The ignorequeryprefix configuration did not take effect

### ISSUE THREAD

**Issue by MyWifeIsZeroTwo** [ljharb/qs#437]
ignoreQueryPrefix of parse function is not effective,

Is it because str.replace (/ ^ \? /, '') in the parseQueryStringValues function has no effect,

Should it be replaced with str.replace (/. * \? /, '')
![微信图片_20220321174438](https://user-images.githubusercontent.com/51142680/159237132-42b85484-e027-4096-9332-95d1af69df86.png)

**Comment by ljharb** [comment]
No, it shouldn’t. It’s a query *prefix* - it only applies if it’s the start of the string.

Perhaps instead of passing the query string, you’re trying to pass a full URL, which this package doesn’t support?

**Comment by ljharb** [comment]
I see in your screenshot that’s the problem. The query string in your URL is `?a=1&b=2`, and it’s up to you to separate that out first before using qs.

**Comment by MyWifeIsZeroTwo** [comment]
I see. Thank you for your answer!
