### ISSUE TITLE
How to implement such parsing

### ISSUE THREAD

**Issue by zizhuxuaner** [ljharb/qs#445]
{ a: [], b:{ c: [], }, e: '111' } =====> a=&b[c]=&e=111

How to implement such parsing

**Comment by ljharb** [comment]
Why would you want that? a and b[c] are both empty arrays, so there's nothing there to serialize. `a=` and `b[c]=` mean something different.

**Comment by zizhuxuaner** [comment]
> 你为什么要那个？a 和 b[c] 都是空数组，所以没有什么可以序列化的。`a=`并`b[c]=`意味着不同的东西。

Can I keep fields? Because the backend needs these fields to determine what to submit. For example, I have a checkbox that allows you to select nothing, and the result is an empty array.

**Comment by ljharb** [comment]
The proper way to handle this with checkboxes on the web is a hidden input with the same name, so that the backend makes a decision based on explicit input and never based implicitly on the lack of input.

**Comment by zizhuxuaner** [comment]
> 使用 Web 上的复选框处理此问题的正确方法是在 HTML 中放置在复选框之前的具有相同名称的隐藏输入，以便后端根据显式输入做出决定，而不会隐含地基于缺少输入。



> The proper way to handle this with checkboxes on the web is a hidden input with the same name, placed in the HTML before the checkboxes, so that the backend makes a decision based on explicit input and never based implicitly on the lack of input.

Thank you very much. I know what's wrong with me. Thank you

**Comment by zizhuxuaner** [comment]
> The proper way to handle this with checkboxes on the web is a hidden input with the same name, placed in the HTML before the checkboxes, so that the backend makes a decision based on explicit input and never based implicitly on the lack of input.

Thank you very much. I know what's wrong with me. Thank you
