### ISSUE TITLE
Stringify method with format: "RFC1738" does not encode parentheses -> ( )

### ISSUE THREAD

**Issue by veljko3ap** [ljharb/qs#478]
Hi 👋🏻 

When using `QueryString.stringify(params, { format: 'RFC1738' })` with format "RFC1738" for some reason parentheses do not get encoded. Every other special characters gets encoded except for `(` and `)`. 

Is this by design or is it a bug? 

Kind regards and keep up the good work 🤓

**Comment by dougwilson** [comment]
See #390

**Comment by veljko3ap** [comment]
@dougwilson Thanks for the info, I presumed as much but wanted to verify it :)
