### ISSUE TITLE
feature request : add exclude specific keys to options array 

### ISSUE THREAD

**Issue by mojtabamaslahatbin** [ljharb/qs#499]
in this function `stringify(object, [options]);`

when we have a key in object that we don't want to serialize it , we need to exclude it in options . for example:
i need this :
```
  &orderBy= {"property":"Amount","direction":"desc"}
```
but after serializing params object , result is like this : 
```
&orderBy[property]=Amount&orderBy[direction]=asc
```

**Comment by ljharb** [comment]
I’m not sure what you mean. You have an API that accepts JSON a in a query string? That seems bizarre to me.

**Comment by mojtabamaslahatbin** [comment]
yes unfortunately in this wiered case it accepts JSON a in a query string😄.
but In general, the possibility of excluding a part of the data can be used for different use cases.

**Comment by ljharb** [comment]
Seems like you should already be able to do this with a custom encoder.
