### ISSUE TITLE
`arrayFormat: 'comma'` Does Not Wrap Single Item as Array When Parsing

### ISSUE THREAD

**Issue by jon9090** [ljharb/qs#505]
**Description:**
When using the `arrayFormat: 'comma'` option with `qs.stringify`, an array with a single item is not wrapped as an array when parsed with `qs.parse`. This behavior leads to inconsistencies, especially when expecting the parsed result to always be an array regardless of the number of items.

[stackblitz example](https://stackblitz.com/edit/vitejs-vite-gfy86a?file=src%2Fmain.ts,package.json&terminal=dev)

**Example:**
```javascript
const qs = require('qs');

const arrayWithOneItem = ['apple'];
const options = { arrayFormat: 'comma' };

const queryString = qs.stringify({ fruits: arrayWithOneItem }, options);
console.log(queryString); // Output: "fruits=apple"

const parsed = qs.parse(queryString, options);
console.log(parsed); // Output: { fruits: 'apple' } // Expected: { fruits: ['apple'] }
```

**Expected Behavior:**
When parsing a query string generated with `arrayFormat: 'comma'`, a single item should be wrapped as an array. The expected output should be:
```javascript
{ fruits: ['apple'] }
```

**Actual Behavior:**
The single item is not wrapped as an array:
```javascript
{ fruits: 'apple' }
```

**Environment:**
- `qs` version: ^6.12.1

**Steps to Reproduce:**
1. Create an array with a single item.
2. Use `qs.stringify` with `arrayFormat: 'comma'`.
3. Parse the resulting query string with `qs.parse` using the same `arrayFormat`.

**Additional Context:**
This behavior causes issues when the consistency of data types is important, particularly when handling query strings with arrays that might have a variable number of items.

**Comment by ljharb** [comment]
That’s what the commaRoundTrip option is for in stringify.
