### ISSUE TITLE
`parse`: add new option to throw when `parameterLimit` is reached

### ISSUE THREAD

**Issue by ljharb** [ljharb/qs#515]
Perhaps instead, add a new option that throws whenever *any* limit is reached, including `arrayLimit`.

See https://github.com/expressjs/express/issues/5878

**Comment by IamLizu** [comment]
Hey @ljharb 👋 

I would like to work on this.

**Comment by ljharb** [comment]
@IamLizu no need to "claim" issues in open source :-) just make a PR for anything that has a "help wanted" label

**Comment by IamLizu** [comment]
Hey @ljharb 👋 

Can we do the implement the `arrayLimit` check in a different PR? If yes, I would enable #517 for review.

**Comment by ljharb** [comment]
I think it'd be important to add it in the same PR, otherwise we'd need two options.

**Comment by IamLizu** [comment]
Agreed 🤝

And thanks for the early review on the PR 🙏
