### ISSUE TITLE
Parse booleans & numbers

### ISSUE THREAD

**Issue by xpepermint** [ljharb/qs#91]
```js
// now
Qs.parse('a=true');    // { a: 'true' }
Qs.parse('a=21.31');    // { a: '21.31' }
// but I would expect boolean
var obj = Qs.parse('a=true');    // { a: true }
Qs.parse('a=21.31');    // { a: 21.31 }
```
Currently I use `express-query-boolean` package which parses `true` and `false` strings into boolean but it would be great to have this feature included in `qs`.

**Comment by nlf** [comment]
My current feeling is that this belongs elsewhere. There are so many conversion patterns that could take place that I don't really want to open the can of worms of implementing them all here. Unless there's a large demand for this, I'm going to say no.

Leaving open for discussion, however.

**Comment by xpepermint** [comment]
OK, I made a plugin for now https://github.com/xpepermint/query-types.

**Comment by davidraleigh** [comment]
I think the @xpepermint request is valid. I was disappointed to see that this isn't a feature. That parse assumes all numbers are strings makes it not so helpful.

**Comment by travist** [comment]
This is actually a problem I am facing using the very popular https://github.com/request/request library. What I am running into is that my REST api is outputting booleans as ```true``` and ```false```. However, when a PUT request is made, this library uses this library to convert it to a querystring, which this then turns all of my booleans into strings breaking the app. I am curious why this library is converting booleans and numbers to strings.  Its a pretty easy fix, and I am willing to submit a pull request.

**Comment by jdiaz5513** [comment]
Part of me wants this too, but automatic type coersion here is troublesome. What if you wanted `"true"` as a string? Or `"21.33"` as a string? I often deal with currency amounts formatted as strings to avoid floating point precision loss.

In particular if you're allowing user input to show up in the query string, all someone has to do is type in `true` where you were expecting a string and good luck avoiding a crash there.

At least the current behavior is predictable and very well defined.

**Comment by travist** [comment]
Thanks for the information. I am no longer blocked by this, so I think I can get by without this change. I was actually able to get around this using https://github.com/visionmedia/superagent instead of https://github.com/request/request (which uses querystring for posts). I can only assume that ```superagent``` does not use query string method for posting information, but I have not dug deep enough yet to determine what is actually different. All I know is my JSON object is not altered from a GET to a POST with ```superagent``` vs ```request.js```. This nugget may prove helpful for anyone else running into this same issue with ```request.js```.

**Comment by DesignByOnyx** [comment]
The plugin created by @xpepermint worked for me and will likely work for others who need it. I agree with the fact that I don't think `qs` should do this for you and people should opt in to this type coercion if they need it. For example, I have some string fields which are actually going to hold values such as "1456" some of the time. I know that the plugin will convert this to a number, but I also know that my data store will save it as a string - so this works for me. If my data store didn't do this, I wouldn't mind calling toString() on a few fields before saving.

**Comment by ljharb** [comment]
I'm happy to consider a way for users to opt in to automatic coercion - but I wouldn't want that by default.

I'm closing this for now, but am happy to reopen it if it warrants further discussion or work.

**Comment by malowitzki** [comment]
Could there not be some way of indicating coercion on a case-by-case basis, using a special character maybe? For example, we could have http://example.com/api/todos/?completed@=true&id@=1, and that would indicate that we want `'completed'` and `'id'` to be coerced, so we'd get `{ completed: true, id: 1 }`... but if we just did completed=1&id@=1, then only id would be coerced, so we'd get `{ completed: 'true', id: 1 }`. 

We could have the special character either in the property name, or in the value itself, and we could put it either at the beginning or the end (although I like it right up next to the = sign).

**Comment by ljharb** [comment]
That seems very inelegant - you'd need to support that special character in your server code as well as your client code.

In other words, there's no standard for using some kind of special character, so I think it'd be a very bad idea to codify that into `qs`.

**Comment by malowitzki** [comment]
Can't say I agree... is the []= syntax standard? It's commonly used, but I don't think it's any kind of standard, as far as I can see, yet qs supports it. 

Besides, choosing a character isn't a _huge_ ask, especially when the default is provided. People can just construct their urls in the client using @=, and then the server would coerce just those values. If they want to always coerce, they can easily set the coercion character to an empty string.

Anyways, it's your tool. I might go ahead spin something off.

**Comment by dougwilson** [comment]
> is the []= syntax standard? It's commonly used, but I don't think it's any kind of standard, as far as I can see, yet qs supports it. 

It is specified in http://www.w3.org/TR/html-json-forms/ , yes. It was working being done to create a standard, through that work has been stopped now.

**Comment by Sigfried** [comment]
I was here with the same issue and I just solved it like: 

```
const myqs = {
  stringify: obj=>encodeURI(JSON.stringify(obj)),
  parse: json=>JSON.parse(decodeURI(json||'{}'))
}

```

**Comment by mmcgahan** [comment]
Adding my +1 to this feature request and linking it to the [previous discussion](https://github.com/tj/node-querystring/issues/34) in the original package that `qs` is based on. 

There's definitely a lot of support and use cases for the feature, and I think making it opt-in would be great with a `coerce` option in `qs.parse`.

**Comment by ljharb** [comment]
@mmcgahan You can already provide your own encoder and decoder, deciding for yourself when "true" means a boolean versus a string - I'm not sure how that decision could ever be codified inside `qs` or `node-querystring` in a way that makes sense.

**Comment by mmcgahan** [comment]
ah, `decoder` is perfect for me. I didn't see the docs in the stringify section - thanks!

**Comment by izelnakri** [comment]
Hi, I'm actually disappointed that this issue is closed. I see so many issues raising the same boolean problem.

Heres my suggestion: its ok to not have this behavior by default, we can just have { allowBooleans: true } options to qs.parse() just like many other existing options out there..

**Comment by ljharb** [comment]
@izelnakri again, you can already do this yourself: https://github.com/ljharb/qs/issues/91#issuecomment-269808663

The issue remains that "true" might be the string "true" or a boolean true; there's no way to know for sure, so since that knowledge is highly specific to your application and your codebase, the only solution *that makes any sense* is for that knowledge to live in your application and your codebase - via a custom encoder/decoder.

**Comment by malowitzki** [comment]
@ljharb Seems like this issue still gets the occasional +1 because there is demand in the community for a basic level of decoding built into this package on an opt-in basis. 

The "true" string case comes up so often, and in most cases is so obviously something that you'd want coerced, that people want a common package that will do such basic decoding. I'd bet that 99% of the time, coercing "true" to a boolean would be preferable. I'd make a similar bet about coercing "123" to an integer. Given that these are such common use cases, I think it makes at least _some_ sense that there might be an opt-in option in the common querystring builder that we all use. If _everyone_ (or 99% of everyone) is implementing these basic coercion cases in their own application-relevant decoders, it would save a lot of lines of code in the long run.

I'm a little more educated now re: standards, and I understand the reluctance to set a de facto standard by implementing it in this library. Maybe a separate package that provides a basic extensible decoder is a better solution (I haven't looked for one recently). However, I still think that including it as an opt-in option (i.e. a non-standard option) in this package as @izelnakri suggests, avoids this problem, because it's not the default functionality: It's just a very lightweight enhancement that allows basic encoding/decoding _if you want to use it_.

That's my two cents, but obviously I'm way past this issue by now.

**Comment by peteboere** [comment]
It's pretty trivial to please most use cases by using the `decoder` option.   Though I appreciate this is not a robust solution.   There would need to be some special syntax to mark non-string type values in the querystring itself.

`````js
qs.parse(data, {
    decoder(value) {
        if (/^(\d+|\d*\.\d+)$/.test(value)) {
            return parseFloat(value);
        }

        let keywords = {
            true: true,
            false: false,
            null: null,
            undefined: undefined,
        };
        if (value in keywords) {
            return keywords[value];
        }

        return value;
    }
});
`````

**Comment by ljharb** [comment]
Also with our decoder code, by using `in`, a value of “toString” will return a function. Use `Object.prototype.hasOwnProperty.call`  instead.

**Comment by davidfurlong** [comment]
> qs.parse(data, {
>     decoder(value) {
>         if (/^(\d+|\d*\.\d+)$/.test(value)) {
>             return parseFloat(value);
>         }
> 
>         let keywords = {
>             true: true,
>             false: false,
>             null: null,
>             undefined: undefined,
>         };
>         if (value in keywords) {
>             return keywords[value];
>         }
> 
>         return value;
>     }
> });

this doesn't seem to work for me.

**Comment by waynebloss** [comment]
Why not just delimit strings like JSON does?

**Comment by ljharb** [comment]
@waynebloss because HTTP query strings aren't encoded like JSON is, so that would break a bunch of serverside implementations.

**Comment by waynebloss** [comment]
Thanks @ljharb, I was thinking that anyone using this library would be doing so for its ability to send a graph instead of a flat structure and therefore, you'd have to use the same parser protocol on the server anyway.

**Comment by nursultan156** [comment]
meet the same problem.
why, don't you just encode and decode quotation mark " ?
if 'a=true', decode as { a: true }
if 'a="true"' (url encoded version will be 'a=%22true%22'), decode as {a:"true"}
this is a standard url encoding

**Comment by ljharb** [comment]
@nursultan156 in no way is that a "standard", that's the problem. It's certainly one reasonable solution, but the *actual standard* is that `a=true` means a string `true`, and `a="true"` means a string `"true"`, and I'm quite sure there are plenty of websites that rely on this.

**Comment by nursultan156** [comment]
@ljharb what if, while encoding, you wold just wrap all values (except numbers and booleans) in extra quotation marks, then while decoding unwrap them, but those which doesn't have extra quotation marks try to parse as int or boolean.

**Comment by ljharb** [comment]
@nursultan156 there's no amount of quotes that would work, because a billion quotes would still be parsed as normal parts of the string.

**Comment by nursultan156** [comment]
@ljharb as an example:
`foo: {
        bar: 'baz'
    }` will be encoded as foo[bar]="baz", 
`foo: {
        bar: 123
    }` will be encoded as foo[bar]=123, 
`foo: {
        bar: '123'
    }` will be encoded as foo[bar]="123", 
`foo: {
        bar: true
    }` will be encoded as foo[bar]=true, 
`foo: {
        bar: 'true'
    }` will be encoded as foo[bar]="true", 
`foo: {
        bar: '"baz"'
    }` will be encoded as foo[bar]=""baz"", 
`foo: {
        bar: '""billions of marks""'
    }` will be encoded as foo[bar]="""billions of marks"""
give example that wouldn't work

**Comment by ljharb** [comment]
@nursultan156 i understand what you're suggesting, but that's not what "every webserver" would expect, and that's not a standard.

**Comment by nursultan156** [comment]
@ljharb it would be good adding it as option

**Comment by ljharb** [comment]
@nursultan156 it already exists; use a custom encoder.

**Comment by waynebloss** [comment]
Building query strings with deeply nested values delimited by square brackets is also a completely non-standard that all web servers won't expect, so I'm not sure why the insistence on limiting developers to existing standards.

What's a standard webserver going to do with a key like "[a][b][c][d]" anyway? For that key to be useful, you're going to use something that understands that key on the webserver too so standards have quite gone out the window by this point!

The suggested option would parse fine by all webservers everywhere.

**Comment by waynebloss** [comment]
Furthermore, when I'm building apps they're just for my server and not all web servers everywhere. So if some _other_ middle/caching/proxy/load-balancing server parsed my query value as `"hello"` instead of `hello`, everything would still work and it wouldn't be the end of the world.

Not being able to parse things correctly is much more annoying than being "non-standard" IMO.

**Comment by waynebloss** [comment]
In the end, it's up to whatever @ljharb wants to do since he's the sheriff around these parts.

You can always fork and advertise the advantages of your lib!

**Comment by ljharb** [comment]
@waynebloss It's definitely standard, and something all Rails and PHP and node express servers would expect, which is a significant portion of the entire internet.

I totally agree that as long as you're pairing *your* server with *your* client config then everything is fine! You can already do everything asked for in this proposal by providing a custom encoder, so I'm not sure why you'd need to fork :-)

**Comment by waynebloss** [comment]
@ljharb I would prefer a simple portable, configurable option over a chunk of code that I have to copy to every project. The only other reason I say to fork is because that's a common refrain in conversations such as these - the option is always there.

Perhaps wrapping qs in another package would be a more agreeable compromise in this case.

**Comment by waynebloss** [comment]
It's pretty funny though, that the original poster here says that they use `express-query-boolean` which is already a package for this kind of logic that they feel is too burdensome to include in their projects.

I can't say that I disagree very much. The package overload is real.

**Comment by nursultan156** [comment]
found the solution that helped me, instead of passing this:
`foo: { bar: 1000 } will be encoded as foo[bar]=1000`
i pass this:
`foo: JSON.stringify({ bar: 1000 }) will be encoded as foo="{"bar":1000}"`

**Comment by stubar** [comment]
Generally agree with @ljharb here, maybe a 1 line note in the main readme.md to summarise how types are cast would help.  Also accept the point that pasting the decoder function around is a pain and not that pretty.  I would export a locally augmented version of qs in your project in this case rather than a new wrapper npm package (if that's what was meant by @waynebloss).

**Comment by crobinson42** [comment]
## SOLUTION

Extending the default `qs.decoder()` method with logic to test for `Int` and `Bool`:

```
qs.parse(request.querystring, {
      decoder(str, decoder, charset) {
            const strWithoutPlus = str.replace(/\+/g, ' ');
            if (charset === 'iso-8859-1') {
              // unescape never throws, no try...catch needed:
              return strWithoutPlus.replace(/%[0-9a-f]{2}/gi, unescape);
            }

            if (/^(\d+|\d*\.\d+)$/.test(str)) {
              return parseFloat(str)
            }

            const keywords = {
              true: true,
              false: false,
              null: null,
              undefined,
            }
            if (str in keywords) {
              return keywords[str]
            }

            // utf-8
            try {
              return decodeURIComponent(strWithoutPlus);
            } catch (e) {
              return strWithoutPlus;
            }
          }
})
```

**Comment by chillyistkult** [comment]
With @crobinson42 solution what would you suggest to do if you really want to have a param encoded as a string even if it could be decoded as a number?

**Comment by AndreiMotinga** [comment]
with all this conversation above I still have no idea how to achieve this. 
It would be nice to be able to do something like
`let search = qs.parse(window.location.search, { arrayFormat: "bracket", integer: true })`

**Comment by ljharb** [comment]
@AndreiMotinga based off of https://github.com/ljharb/qs/issues/91#issuecomment-437926409:
```jsx
qs.parse(window.location.search, { ignoreQueryPrefix: true, arrayFormat: 'bracket', decoder(str, decoder, charset) {
  const strWithoutPlus = str.replace(/\+/g, ' ');
  if (charset === 'iso-8859-1') {
  // unescape never throws, no try...catch needed:
    return strWithoutPlus.replace(/%[0-9a-f]{2}/gi, unescape);
  }

  if (/^(\d+|\d*\.\d+)$/.test(str)) {
    return parseFloat(str)
  }

  const keywords = {
    true: true,
    false: false,
    null: null,
    undefined,
  };
  if (str in keywords) {
    return keywords[str]
  }

  // utf-8
  try {
    return decodeURIComponent(strWithoutPlus);
  } catch (e) {
    return strWithoutPlus;
  }
} });
```

**Comment by Ashtonian** [comment]
Wanted something a bit more configurable with additional options such as `ignoreEmptyString`
```js
function newDecoder (parseNumbers = true, parseBool = true, ignoreNull = true, ignoreEmptyString = true) {
  return function decoder (str, decoder, charset) {
    const strWithoutPlus = str.replace(/\+/g, ' ')
    if (charset === 'iso-8859-1') {
      // unescape never throws, no try...catch needed:
      return strWithoutPlus.replace(/%[0-9a-f]{2}/gi, unescape)
    }

    if (parseNumbers && /^(\d+|\d*\.\d+)$/.test(str)) {
      return parseFloat(str)
    }

    if (ignoreEmptyString && str.length === 0) {
      return
    }

    const keywords = {
      null: ignoreNull ? undefined : null,
      undefined
    }

    if (str in keywords) {
      return keywords[str]
    }

    const boolKeywords = {
      true: true,
      false: false
    }

    if (parseBool && str in boolKeywords) {
      return boolKeywords[str]
    }

    try {
      return decodeURIComponent(strWithoutPlus)
    } catch (e) {
      return strWithoutPlus
    }
  }
}
 ```

**Comment by sfaujour** [comment]
When i use your solution with `comma: true`, it won't work.
```
TypeError: val.indexOf is not a function 
at parseQueryStringValues (node_modules/qs/lib/parse.js:86:41)
```

When i edit this line and add `typeof val !== 'boolean'` as validation then it works.

**Comment by ljharb** [comment]
@sfaujour a custom decoder is required to only return a string.

**Comment by sirajalam049** [comment]
isn't it good to have an option as parseBool and parseNumber just like [query-string](https://www.npmjs.com/package/query-string) have?

**Comment by ljharb** [comment]
That package's docs for parseBool say "if it's a boolean", and "if it's a number", but don't explicitly describe how they determine that. In some server frameworks, a boolean is yes/no/true/TRUE/false/FALSE/on/off/1/0. In others, it may just be true/false. In some, it might be cierto/falso, perhaps.

In other words, having these options that arbitrarily encode one person's opinion about "how to determine them" is flawed _at best_, and I'd prefer not to have them at all. You can, however, use a custom decoder to decide *for yourself* what "it's a boolean" means, and then qs wouldn't run the likely risk of having nonsensical options.

**Comment by hadiaec20h** [comment]
on/off/1/0/yes/no are basically custom type of values which represent boolean and not converting to boolean is reasonable. But what would be the use of true/TRUE/false/FALSE as string other than representing a boolean value?

**Comment by ljharb** [comment]
@hadiaec20h https://www.engadget.com/icloud-true-last-name-lock-out-192224309.html

**Comment by DesignByOnyx** [comment]
The thing is, this type of "auto-coercion" code must be written to iterate over data and interpret certain fields as scalar/primitive values (numbers, booleans, etc). That code can be written in two places:

1. **The `qs` library can implement it** - this would be a breaking change with guaranteed adverse affects. You have to worry about "how do I turn this off", which results in this library having more API, which means more maintenance/documentation, which leads to more "why is this happening" types of bugs, and a whole host of other potential issues.
2. **You can implement it yourself on a per-project basis** - this give you full control over which values should be coerced, the `qs` library stays leaner and more predictable, and everybody is happy - even the developer who had to spend 15 minutes googling and copying code into their project.

Option 2 is a clear winner hear. I propose that the docs should link to a code tried-and-true coercion snippet for easy copy/paste and lay this issue to rest.

**Comment by ljharb** [comment]
Happy to accept PRs to improve the docs.

**Comment by SteveOscar** [comment]
> @AndreiMotinga based off of [#91 (comment)](https://github.com/ljharb/qs/issues/91#issuecomment-437926409):
> 
> ```js
> qs.parse(window.location.search, { ignoreQueryPrefix: true, arrayFormat: 'bracket', decoder(str, decoder, charset) {
>   const strWithoutPlus = str.replace(/\+/g, ' ');
>   if (charset === 'iso-8859-1') {
>   // unescape never throws, no try...catch needed:
>     return strWithoutPlus.replace(/%[0-9a-f]{2}/gi, unescape);
>   }
> 
>   if (/^(\d+|\d*\.\d+)$/.test(str)) {
>     return parseFloat(str)
>   }
> 
>   const keywords = {
>     true: true,
>     false: false,
>     null: null,
>     undefined,
>   };
>   if (str in keywords) {
>     return keywords[str]
>   }
> 
>   // utf-8
>   try {
>     return decodeURIComponent(strWithoutPlus);
>   } catch (e) {
>     return strWithoutPlus;
>   }
> } });
> ```

Note that this check for floats (`/^(\d+|\d*\.\d+)$/.test(str)`) misses negative values. I'm working with lat/long and it bit me.

**Comment by jarraga** [comment]
> 
I didn't realize this super simple and native solution, thanks!

> I was here with the same issue and I just solved it like:
> 
> ```
> const myqs = {
>   stringify: obj=>encodeURI(JSON.stringify(obj)),
>   parse: json=>JSON.parse(decodeURI(json||'{}'))
> }
> ```

I didn't realize this super simple and native solution, thanks!

**Comment by tientran0019** [comment]
It's work for me
`qs.parse(request.querystring, {
      decoder(str: string, defaultDecoder: qs.defaultDecoder, charset: string, type: 'key' | 'value') {
	if (type === 'value' && /^(?:-(?:[1-9](?:\d{0,2}(?:,\d{3})+|\d*))|(?:0|(?:[1-9](?:\d{0,2}(?:,\d{3})+|\d*))))(?:.\d+|)$/.test(str)) {
		return parseFloat(str);
	}

	const keywords = {
		true: true,
		false: false,
		null: null,
		undefined: undefined,
	};
	if (type === 'value' && str in keywords) {
		return keywords[str];
	}

	return defaultDecoder(str, defaultDecoder, charset);
    }, 
})`

**Comment by micobarac** [comment]
I extended [https://github.com/xpepermint/query-types](https://github.com/xpepermint/query-types):

`query.middleware.ts`

```ts
import qs from 'qs';

type ParsedValue = string | number | boolean | Date | Record<string, unknown> | unknown[];

function isObject(val: unknown): val is Record<string, unknown> {
  return val !== null && typeof val === 'object' && val.constructor === Object;
}

function isNumber(val: unknown): boolean {
  return !isNaN(parseFloat(String(val))) && isFinite(Number(val));
}

function isBoolean(val: unknown): boolean {
  return val === 'false' || val === 'true';
}

function isDate(val: unknown): boolean {
  if (!(typeof val === 'string' || typeof val === 'number' || val instanceof Date)) return false;
  return !isNaN(new Date(val).getTime());
}

function isArray(val: unknown): val is unknown[] {
  return Array.isArray(val);
}

function isNestedArray(val: unknown): val is unknown[][] {
  return Array.isArray(val) && val.length > 0 && Array.isArray(val[0]);
}

function parseValue(val: unknown): ParsedValue | null {
  if (typeof val === 'undefined' || val === 'null' || val === '') {
    return null;
  } else if (isNumber(val)) {
    return parseNumber(val);
  } else if (isBoolean(val)) {
    return parseBoolean(val);
  } else if (isDate(val)) {
    return parseDate(val);
  } else if (isNestedArray(val)) {
    return val.map((arr) => parseArray(arr));
  } else if (isArray(val)) {
    return parseArray(val);
  } else if (isObject(val)) {
    return parseObject(val);
  } else {
    return val as string;
  }
}

function parseObject(obj: Record<string, unknown>): Record<string, ParsedValue> {
  const result: Record<string, ParsedValue> = {};
  for (const key in obj) {
    const val = parseValue(obj[key]);
    if (val !== null) result[key] = val;
  }
  return result;
}

function parseNumber(val: unknown): number {
  return Number(val);
}

function parseBoolean(val: unknown): boolean {
  return String(val) === 'true';
}

function parseDate(val: unknown): Date | string {
  const parsed = new Date(val as string | number | Date);
  return isNaN(parsed.getTime()) ? String(val) : parsed;
}

function parseArray(arr: unknown[]): ParsedValue[] {
  return arr.map((item) => parseValue(item)).filter((item): item is ParsedValue => item !== null);
}

function queryMiddleware(options?: qs.IParseOptions): (str: string) => Record<string, ParsedValue> {
  return function (str: string): Record<string, ParsedValue> {
    try {
      return parseObject(qs.parse(str, options));
    } catch (error) {
      console.error('Query parsing failed:', error);
      return {};
    }
  };
}

export { queryMiddleware };
```

In my case, I use it in NestJS application.

`main.ts`

```ts
import { RequestMethod } from '@nestjs/common/enums';
import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import { setupSwagger } from 'swagger';
import { AppModule } from './app.module';
import { queryMiddleware } from './core/middleware/query.middleware';

async function bootstrap() {
  // https://docs.nestjs.com/migration-guide#express-v5
  const app = await NestFactory.create<NestExpressApplication>(AppModule);
  //app.set('query parser', 'extended');
  app.set('query parser fn', queryMiddleware()); // Custom middleware with extended types processing

  app.enableCors();

  app.setGlobalPrefix('api', {
    exclude: [{ path: 'health', method: RequestMethod.GET }]
  });

  setupSwagger(app);

  await app.listen(3000);
}
bootstrap();
```

The middleware will take care of:

`undefined`, `null`, `empty`, `number`, `boolean`, `date`, `array` ... query params.
