### ISSUE TITLE
Inadequate encoding of Buffers

### ISSUE THREAD

**Issue by seishun** [ljharb/qs#94]
Let's say I want to send some percent-encoded binary data.

```js
> Qs.stringify({a: new Buffer([0x10, 0x20])})
'a=%10%20'
```

So far so good.

```js
> Qs.stringify({a: new Buffer([0xff, 0xff])})
'a=%EF%BF%BD%EF%BF%BD'
```

What? I expected `'%FF%FF'`!

The problem is that it simply [calls `toString` on the Buffer](https://github.com/hapijs/qs/blob/0c6f2a6318c94f6226d3cf7fe36094e9685042b6/lib/stringify.js#L34), which attempts to decode it as UTF-8. It doesn't make sense, since it is then [encoded](https://github.com/hapijs/qs/blob/0c6f2a6318c94f6226d3cf7fe36094e9685042b6/lib/utils.js#L84) back into UTF-8. This round-trip could only be lossless if the original Buffer is a UTF-8 encoded string in the first place, in which case one would just use a string instead.

**Comment by nlf** [comment]
I'm not sure I totally understand what end result you're trying to achieve. This module is for parsing HTTP querystring parameters, are you sending binary data in an HTTP request?

**Comment by seishun** [comment]
> are you sending binary data in an HTTP request?

Yes.

**Comment by nlf** [comment]
as a query parameter? that seems like bad design to me. i can look into making buffer decoding configurable, but i'm not entirely sure it'll work like you want it to anyway. `0xff` would still be interpreted as a character, and would be URI encoded as such to be sure that it can be transmitted as a query parameter. Even stringifying the buffer as binary still yields a different result:

```
> encodeURIComponent(new Buffer([0xff]).toString('binary'))
'%C3%BF'
```

**Comment by seishun** [comment]
>as a query parameter?

Yes, in the POST body.

>0xff would still be interpreted as a character, and would be URI encoded as such to be sure that it can be transmitted as a query parameter.

Query parameters are transmitted as percent-encoded byte sequences, so strings have to be encoded in UTF-8. There is no need to do any encoding for Buffers, since they are already byte sequences - they just have to be percent-encoded.

>Even stringifying the buffer as binary still yields a different result:

Sure, you're giving `encodeURIComponent` a string consisting of a single character with value 255, which is "ÿ". Since the character "ÿ" is not ASCII, it becomes multi-byte when encoded in UTF-8.

**Comment by nlf** [comment]
this would also require changes to parsing to be able to reconstruct a buffer from a byte sequence. i'm still not sure i understand why your POST body is being parsed by this module, or why you're transmitting binary data directly without encoding. your problem would be solved, for example, if you were to base64 encode your binary before sending it.

**Comment by seishun** [comment]
>this would also require changes to parsing to be able to reconstruct a buffer from a byte sequence.

Why, for symmetry? I suppose you could just return a decoded Buffer [here](https://github.com/hapijs/qs/blob/0c6f2a6318c94f6226d3cf7fe36094e9685042b6/lib/utils.js#L80). Something like this should work:

```js
new Buffer(str.replace(/%(..)/g, function(match, p1) { return String.fromCharCode(parseInt(p1, 16)); }), 'binary')
```

Although it uses the deprecated 'binary' encoding. There are probably better ways.

>your problem would be solved, for example, if you were to base64 encode your binary before sending it.

It wouldn't, because the server doesn't accept base64 encoded data.

**Comment by nlf** [comment]
yes, for symmetry. i'll have to think about how best to implement this.

**Comment by martinheidegger** [comment]
Note: this is a serious issue when trying to deal with a service that uses encoding other than utf8. Here in japan unfortunately many services still use ShiftJIS.

**Comment by martinheidegger** [comment]
@nlf This issue should be solved by #161 in 6.2.0

**Comment by ljharb** [comment]
@seishun please reopen if this is not resolved.

**Comment by vith** [comment]
I've just run into the same problem. It would be nice if users of this library didn't have to reimplement the escaping logic it provides.

This is what I've done in a PR to a project that uses qs: https://github.com/vith/js-ipfs-api/commit/31a473860f8034a68bd6f84f0a0002c124c47425

Have I overlooked something? Passing a binary string via `Buffer.prototype.toString('binary')` into `require('qs/lib/utils').encode` still mangles the bytes so there was no way to reuse just the first part of that function that encapsulates the knowledge of which characters can be passed through without escaping.
